# ============================================
# 123MiniApps.online, Blog articles (original general explainers)
# Consumed by build-blog.py via POST_MODULES.
# ============================================

POSTS = [
 {
 'slug': 'why-1tb-drive-shows-931gb',
 'icon': '💾',
 'nav_title': 'Why a 1TB drive shows 931GB',
 'headline': 'Why does my 1TB hard drive only show 931GB?',
 'title': 'Why Does My 1TB Drive Show 931GB? The Real Explanation',
 'standfirst': 'Nothing is missing and nobody is cheating you. Your drive and your operating system are counting in two different number systems.',
 'description': 'Your 1TB drive shows as 931GB because manufacturers count in powers of 1000 and Windows counts in powers of 1024. Here is exactly where the difference comes from.',
 'published': '2026-02-04',
 'keywords': ['1tb drive 931gb', 'why is my hard drive smaller', 'gb vs gib', 'decimal vs binary storage', 'missing hard drive space'],
 'related_tools': [('file-size-converter', 'File Size Converter'), ('unit-converter', 'Unit Converter')],
 'body': [
 ('p', 'You bought a 1TB drive. You plug it in, open your file manager, and it reports 931GB. Roughly 69GB has apparently evaporated before you have saved a single file. This is the single most common storage question on the internet, and the answer is not what most people assume.'),
 ('p', '<strong>Nothing is missing.</strong> The drive contains exactly what it says on the box. What you are seeing is two different definitions of the word gigabyte, both in active use, producing two different numbers for the same physical hardware.'),
 ('h2', 'Two definitions of a gigabyte'),
 ('p', 'Every other unit prefix in science means a power of ten. A kilometre is 1,000 metres. A kilogram is 1,000 grams. When the SI system defines <em>kilo</em>, it means exactly 1,000.'),
 ('p', 'Computers, however, address memory in powers of two. The closest power of two to 1,000 is 2¹⁰, which is 1,024, near enough that early computer scientists borrowed the SI prefixes and quietly redefined them. A kilobyte became 1,024 bytes, a megabyte 1,024², and a gigabyte 1,024³.'),
 ('p', 'That approximation is fine at small scales. A kilobyte defined as 1,024 is only 2.4% larger than one defined as 1,000. But the error compounds with every prefix you climb.'),
 ('table', ['Unit', 'Decimal (×1000)', 'Binary (×1024)', 'Difference'], [['Kilobyte', '1,000', '1,024', '2.4%'], ['Megabyte', '1,000,000', '1,048,576', '4.9%'], ['Gigabyte', '1,000,000,000', '1,073,741,824', '7.4%'], ['Terabyte', '1,000,000,000,000', '1,099,511,627,776', '10.0%']]),
 ('h2', 'Where the 931 comes from'),
 ('p', 'Storage manufacturers use the decimal definition. A drive sold as 1TB contains 1,000,000,000,000 bytes. That is not marketing sleight of hand, it is the SI definition, and it is what the standards say a terabyte is.'),
 ('p', 'Windows, however, divides that byte count by 1,024 three times and then labels the result "GB". Do the arithmetic yourself:'),
 ('ol', ['1,000,000,000,000 ÷ 1,024 = 976,562,500 (kibibytes)', '976,562,500 ÷ 1,024 = 953,674 (mebibytes)', '953,674 ÷ 1,024 = 931 (gibibytes)']),
 ('p', 'So the drive genuinely holds 1 decimal terabyte <em>and</em> 931 binary gigabytes. Both numbers describe the same silicon. The confusion exists entirely because Windows displays a binary calculation using a decimal label.'),
 ('callout', 'The one-line version', 'Manufacturers measure in powers of 1000. Windows measures in powers of 1024 but writes "GB" anyway. The hardware is identical; only the arithmetic differs.'),
 ('h2', 'Why macOS shows a different number'),
 ('p', 'If you plug the same drive into a Mac, it reports 1TB. Apple changed this in macOS 10.6 Snow Leopard, back in 2009, switching Finder to decimal reporting so that the operating system agrees with the box. Linux distributions vary, many command-line tools default to binary but label it correctly as GiB.'),
 ('p', 'This is why the same drive can honestly be described as 1TB, 931GB or 931GiB depending on who is doing the describing. None of them is lying.'),
 ('h2', 'The prefixes that would have solved this'),
 ('p', 'The International Electrotechnical Commission introduced unambiguous binary prefixes in 1998: kibibyte (KiB), mebibyte (MiB), gibibyte (GiB) and tebibyte (TiB). Under that scheme, your drive is 1TB and also 931GiB, and both statements are precise.'),
 ('p', 'The prefixes are correct, they are standardised, and almost nobody uses them. They survive mainly in Linux tooling and technical documentation. Windows has never adopted them, which is why this question keeps getting asked.'),
 ('h2', 'The other missing space'),
 ('p', 'There is a second, smaller effect that people sometimes conflate with this one. Formatting a drive consumes some capacity for the filesystem itself, the allocation tables, journal and metadata that let the operating system find your files. On NTFS this is typically well under 1% of the drive.'),
 ('p', 'So a 1TB drive shows roughly 931GB from the counting difference, and then loses a few more gigabytes to formatting. If you are seeing substantially less than 931GB on a nominally empty 1TB drive, that is worth investigating, hidden recovery partitions and system restore allocations are the usual culprits.'),
 ('tool', 'file-size-converter', 'File Size Converter', 'Enter any size and see it in both conventions side by side, along with the exact byte count and a transfer-time estimate. It runs entirely in your browser.'),
 ('h2', 'The networking trap, while we are here'),
 ('p', 'Storage is measured in bytes. Network speed is measured in <em>bits</em>. There are eight bits in a byte, so a 100 Mbps connection moves at most 12.5 megabytes per second, and less after protocol overhead, typically around 11 MB/s in practice.'),
 ('p', 'This catches people constantly. If your 100 Mbps connection seems to download at "only" 11 MB/s, it is working correctly. The lowercase b means bits and the uppercase B means bytes, which is a distinction that has caused more confusion than almost any other convention in computing.'),
 ('h2', 'Was there ever a lawsuit about this?'),
 ('p', 'Yes, several. Class actions were brought against major drive manufacturers in the United States in the early 2000s arguing that decimal labelling was deceptive. The manufacturers largely prevailed on the grounds that they were using the internationally standardised definition, but several settled by agreeing to disclose the convention on packaging. That is why drive boxes now carry a line explaining that 1GB equals 1,000,000,000 bytes.'),
 ('h2', 'Why manufacturers and operating systems disagree'),
 ('p', 'The gap exists because two different definitions of a "gigabyte" are both in use. Storage manufacturers use the decimal definition, where one gigabyte is exactly 1,000,000,000 bytes, because that is how the metric system defines the giga prefix everywhere else, a kilometre is 1,000 metres, not 1,024. Most operating systems, however, still report capacity using binary units, where what they label a "GB" is really 1,073,741,824 bytes (properly called a gibibyte, or GiB). Your drive holds the number of bytes the manufacturer promised; the operating system simply divides by the larger binary figure, producing a smaller-looking number.'),
 ('p', 'Neither side is lying. The drive genuinely stores a trillion bytes for a "1 TB" model. Windows just displays that same trillion bytes as roughly 931 because it divides by 1,024 three times instead of 1,000. Some systems, including macOS in recent versions, switched to the decimal definition specifically to end this confusion, which is why the same drive can show 1,000 GB on a Mac and 931 GB on a Windows PC. The bytes never changed, only the label did.'),
 ('p', 'The courts, in effect, decided the manufacturers were right and the operating systems were the ones being confusing. Two and a half decades later, Windows still has not changed.'),
 ],
 },
 {
 'slug': 'how-long-should-a-password-be',
 'icon': '🔑',
 'nav_title': 'How long should a password be',
 'headline': 'How long should a password actually be?',
 'title': 'How Long Should a Password Be? What the Evidence Says',
 'standfirst': 'Length beats complexity by a wide margin, and most of the rules websites impose make passwords weaker rather than stronger.',
 'description': 'A practical answer grounded in entropy: why length beats symbols, why NIST now advises against composition rules, and what actually protects an account.',
 'published': '2026-02-11',
 'keywords': ['how long should a password be', 'password entropy bits', 'nist password guidelines', 'is a 12 character password secure', 'passphrase vs password'],
 'related_tools': [('password-generator', 'Password Generator'), ('password-strength-checker', 'Password Strength Checker'), ('password-game', 'Password Game')],
 'body': [
 ('p', 'The short answer: <strong>at least 16 characters if you are choosing it yourself, and the maximum the site allows if a password manager is generating it.</strong> Everything else, the capital letter, the number, the exclamation mark, matters far less than the length, and some of it actively makes things worse.'),
 ('p', 'Here is why, with the arithmetic rather than the folklore.'),
 ('h2', 'Entropy, in plain terms'),
 ('p', 'Password strength is measured in bits of entropy. Each bit doubles the number of guesses an attacker needs. A password with 40 bits of entropy requires about a trillion guesses to exhaust; one with 80 bits requires about a trillion trillion.'),
 ('p', 'For a randomly generated password, the calculation is simple: multiply the length by the log base two of the character pool size. Lowercase letters alone give 4.7 bits per character. Adding uppercase takes it to 5.7. Adding digits and symbols takes it to about 6.5.'),
 ('table', ['Password', 'Length', 'Pool', 'Entropy', 'Verdict'], [['<code>Tr0ub4dor&3</code>', '11', '95', '~72 bits on paper', 'Far weaker in reality'], ['<code>correcthorsebatterystaple</code>', '25', '26', '~117 bits', 'Strong'], ['<code>kR7#mQ9$vX2@pL5!</code>', '16', '95', '~105 bits', 'Strong'], ['<code>Password123!</code>', '12', '95', '~79 bits on paper', 'Falls in seconds']]),
 ('p', 'Look at rows one and four. Both score respectably by the raw formula and both are weak in practice. This is the crucial limitation of entropy maths: <strong>it only holds for passwords that were actually generated at random.</strong>'),
 ('h2', 'Why the formula lies about human-chosen passwords'),
 ('p', 'Attackers do not brute-force blindly. They start with lists of passwords leaked from previous breaches, hundreds of millions of real passwords that real people actually chose. Then they apply transformation rules: capitalise the first letter, append a year, swap <code>a</code> for <code>@</code>, add an exclamation mark.'),
 ('p', '<code>Password123!</code> has 79 bits by the formula and appears near the top of every cracking dictionary in existence. It falls instantly. The formula is describing a search space the attacker never has to search.'),
 ('callout', 'The practical implication', 'Entropy maths is a valid measure of a randomly generated password and a poor measure of one a human invented. If you chose it yourself and it follows any recognisable pattern, assume it is substantially weaker than the number suggests.'),
 ('h2', 'What NIST actually recommends now'),
 ('p', 'The US National Institute of Standards and Technology publishes the guidance that most organisations follow, and in Special Publication 800-63B it reversed several rules that had been standard for decades. The current advice is worth knowing because it contradicts what most websites still enforce:'),
 ('ul', ['<strong>Require a minimum of 8 characters</strong>, and permit at least 64.', '<strong>Allow all printable characters</strong>, including spaces and emoji.', '<strong>Do not impose composition rules.</strong> No mandatory uppercase, digits or symbols.', '<strong>Do not force periodic expiry.</strong> Only require a change on evidence of compromise.', '<strong>Check new passwords against breach lists</strong> and reject known-compromised ones.']),
 ('p', 'The reasoning behind dropping composition rules is that they produce predictable output. Told to add a capital and a number, the overwhelming majority of people capitalise the first letter and append a 1. The rule adds almost no real entropy while making the password harder to remember, which pushes people toward reuse, the single most damaging behaviour of all.'),
 ('p', 'Forced 90-day rotation was dropped for the same reason. It reliably produces <code>Spring2026</code> followed by <code>Summer2026</code>, which is worse than a strong password kept indefinitely.'),
 ('h2', 'Passphrases: the honest recommendation'),
 ('p', 'Four or five random words are easier to remember than a string of symbols and mathematically stronger than most of them. Drawing randomly from a 7,776-word list, the standard Diceware list, gives 12.9 bits per word. Five words is 64 bits; six words is 77.'),
 ('p', 'The critical word is <em>random</em>. Words you chose because they mean something to you are not random, and a passphrase built from a memorable phrase is dramatically weaker than one built from dice rolls. Let a generator pick them.'),
 ('tool', 'password-generator', 'Password Generator', "Generates passwords using crypto.getRandomValues(), the browser's cryptographically secure generator, not Math.random(), with rejection sampling to remove modulo bias. Nothing is transmitted; you can verify that in the Network tab."),
 ('h2', 'How long would mine take to crack?'),
 ('p', 'This depends far more on how the site stored your password than on the password itself, which is an uncomfortable thing to realise. Assuming a database has leaked and the attacker is working offline:'),
 ('table', ['Storage method', 'Guesses per second (one GPU)', '16-char random password'], [['Unsalted MD5', '~100 billion', 'Still centuries'], ['SHA-256', '~10 billion', 'Effectively forever'], ['bcrypt (cost 12)', '~20 thousand', 'Effectively forever'], ['Argon2id (tuned)', '~2 thousand', 'Effectively forever']]),
 ('p', "A genuinely random 16-character password is beyond reach under any of these. The reason the storage method still matters enormously is that most people's passwords are not random, and against a weak human-chosen password, the difference between SHA-256 and bcrypt is the difference between cracked in minutes and never cracked."),
 ('h2', 'What matters more than length'),
 ('p', 'Three things beat password length, and it is worth being blunt about them:'),
 ('ol', ['<strong>Uniqueness.</strong> A perfect password used on two sites is only as safe as the less careful of the two. Credential stuffing, trying leaked pairs across other services, is the most common account takeover method there is.', '<strong>Two-factor authentication.</strong> An app-based or hardware second factor defeats credential stuffing entirely, even with a compromised password. This is the single highest-value thing most people can enable.', '<strong>A password manager.</strong> It makes uniqueness free. You stop needing to remember anything except one strong master passphrase, and every other password can be 30 random characters you never see.']),
 ('p', 'If you do one thing after reading this, make it enabling two-factor authentication on your email account. Email is the reset path for everything else you own.'),
 ('tool', 'password-strength-checker', 'Password Strength Checker', 'Scores entropy in bits, estimates offline crack time across four attacker capabilities, and flags the patterns that make a password weaker than its raw score suggests, dictionary words, keyboard runs, leetspeak substitutions and the word-plus-digits pattern.'),
 ('h2', 'So, a number'),
 ('p', 'For a password you have to type and remember: <strong>a 5-word random passphrase</strong>, which is around 25 characters and 64 bits. For anything a password manager handles: <strong>whatever maximum the site permits</strong>, since you will never type it.'),
 ('p', 'And if a site refuses a password because it is "too long" or rejects a space, that tells you something about the rest of its security engineering. It is a reasonable signal to use a unique password there and enable two-factor authentication if it is offered.'),
 ],
 },
 {
 'slug': 'webp-vs-jpeg-vs-png',
 'icon': '🖼️',
 'nav_title': 'WebP vs JPEG vs PNG',
 'headline': 'WebP, JPEG or PNG: which should you actually use?',
 'title': 'WebP vs JPEG vs PNG: Which Image Format to Use and When',
 'standfirst': 'A practical decision guide, plus the two mistakes that waste more bandwidth than choosing the wrong format ever will.',
 'description': 'When to use WebP, JPEG, PNG, AVIF and SVG, with the compression trade-offs explained and the resizing mistake that costs more than format choice.',
 'published': '2026-02-18',
 'keywords': ['webp vs jpeg', 'png vs jpg which is better', 'best image format for web', 'avif vs webp', 'should i use webp'],
 'related_tools': [('image-compressor', 'Image Compressor'), ('image-format-converter', 'Image Format Converter'), ('image-resizer', 'Image Resizer')],
 'body': [
 ('p', 'The short version: <strong>use WebP for almost everything, SVG for anything drawn rather than photographed, and keep JPEG only as a fallback.</strong> PNG has a narrower role than most people give it.'),
 ('p', 'But format choice is not where most sites lose their bandwidth. That comes later in this article, and it is worth skipping ahead for if you only read one section.'),
 ('h2', 'The formats, quickly'),
 ('table', ['Format', 'Compression', 'Transparency', 'Animation', 'Best for'], [['<strong>WebP</strong>', 'Lossy + lossless', 'Yes', 'Yes', 'Almost everything'], ['<strong>AVIF</strong>', 'Lossy + lossless', 'Yes', 'Yes', 'Photos, where encoding time is fine'], ['<strong>JPEG</strong>', 'Lossy only', 'No', 'No', 'Fallback for ancient clients'], ['<strong>PNG</strong>', 'Lossless only', 'Yes', 'No', 'Screenshots, sharp-edged graphics'], ['<strong>SVG</strong>', 'Vector', 'Yes', 'Yes', 'Logos, icons, diagrams']]),
 ('h2', 'Why WebP is the default now'),
 ('p', 'WebP is typically 25% to 35% smaller than JPEG at visually equivalent quality, and roughly 26% smaller than PNG for lossless images. It supports transparency, which JPEG does not, and animation, which PNG effectively does not.'),
 ('p', 'The historical objection was browser support. That objection has expired, every current browser supports WebP, and has for years. If you are still serving JPEG as your primary format out of caution, you are paying a real bandwidth premium for a compatibility problem that no longer exists.'),
 ('p', 'AVIF compresses better still, often another 20% below WebP. Its trade-offs are slower encoding and slightly less universal support. For a photo-heavy site where you encode once and serve many times, AVIF is worth the encode time. For everything else, WebP is the pragmatic choice.'),
 ('h2', 'Where PNG still wins'),
 ('p', 'PNG is lossless, and that matters for a specific category of image: anything with sharp edges and flat colour. Screenshots containing text, UI mockups, logos, diagrams, pixel art.'),
 ('p', "JPEG's compression works by discarding high-frequency detail in 8×8 pixel blocks. That is imperceptible on a photograph of a face and catastrophic on a screenshot of code, you get visible ringing artefacts around every letter. The text turns fuzzy in a way that looks cheap and is genuinely harder to read."),
 ('p', 'But note that <em>lossless WebP</em> also handles this case, and produces smaller files than PNG. The real rule is not "use PNG for graphics" but "use lossless compression for graphics", and WebP does lossless better than PNG does.'),
 ('callout', 'The one thing PNG must never be used for', 'Photographs. A photo saved as PNG can easily be ten times the size of the same photo as WebP with no visible quality benefit. If it came out of a camera, it should be lossy.'),
 ('h2', 'SVG is not really in the same competition'),
 ('p', 'SVG is a vector format, it stores shapes and coordinates rather than pixels. That makes it infinitely scalable and usually tiny for anything geometric. A logo that is 40KB as a PNG might be 2KB as an SVG, and it stays perfectly sharp on any display at any size.'),
 ('p', 'It also has properties no raster format has: you can style it with CSS, animate individual paths, and make it respond to dark mode from inside the file itself. For logos, icons and diagrams, SVG is not a compromise, it is straightforwardly better.'),
 ('p', 'It is useless for photographs, which is the only real limit.'),
 ('h2', 'The mistake that costs more than format choice'),
 ('p', 'Here is the section worth skipping ahead for. <strong>Most oversized images on the web are oversized because of their dimensions, not their format.</strong>'),
 ('p', "File size scales with pixel count. Halving an image's width quarters its pixels and typically cuts the file to around a quarter of its original size. A 4000-pixel-wide photo displayed in an 800-pixel column is carrying twenty-five times more data than the screen can possibly use."),
 ('p', 'Switching that image from JPEG to WebP might save 30%. Resizing it to the width it is actually displayed at saves 96%. The two are not close, and the resize costs no quality whatsoever because the extra pixels were never visible.'),
 ('ol', ['Find the largest size the image is ever displayed at.', 'Double it, for high-density displays.', 'Resize to that. Everything above it is waste.', '<em>Then</em> worry about format and quality settings.']),
 ('tool', 'image-resizer', 'Image Resizer', 'Resize to exact pixels or a percentage, with aspect ratio locking and presets for common web and social sizes. Processed entirely in your browser, the image is never uploaded.'),
 ('h2', 'What quality setting should I use?'),
 ('p', 'JPEG and WebP quality settings are not percentages of anything meaningful. They index into quantisation tables, and the relationship to file size is steeply non-linear.'),
 ('p', 'Dropping from quality 100 to 85 often halves the file with no perceptible difference. Dropping from 50 to 35 saves comparatively little and looks noticeably worse. The useful range is narrow: <strong>75 to 85 for photographs</strong> is where nearly everyone lands after experimenting.'),
 ('p', 'One rule that is absolute: never re-compress a lossy image repeatedly. Each pass discards more information permanently. Always re-encode from the original, never from a previously compressed copy. And converting a JPEG to PNG does not restore anything, you get a larger file containing exactly the same artefacts.'),
 ('tool', 'image-compressor', 'Image Compressor', 'Adjustable quality with a live size readout and a before-and-after comparison, plus a width limit, which usually saves more than the quality slider does.'),
 ('h2', 'Serving more than one format'),
 ('p', 'If you want the smallest possible files without abandoning older clients, the <code>&lt;picture&gt;</code> element lets the browser choose:'),
 ('quote', 'The browser walks the sources in order and takes the first format it understands, falling back to the plain <code>&lt;img&gt;</code> if it recognises none of them. AVIF first, then WebP, then JPEG.'),
 ('p', 'This is genuinely worth doing for a photo-heavy site. For a small site with a handful of images, serving WebP alone is simpler and the difference is not worth the build complexity.'),
 ('h2', 'A decision tree'),
 ('ul', ['<strong>Is it a logo, icon or diagram?</strong> → SVG.', '<strong>Is it a screenshot or has sharp text?</strong> → Lossless WebP, or PNG as fallback.', '<strong>Is it a photograph?</strong> → WebP at quality 80, or AVIF if you can encode it.', '<strong>Does it need transparency?</strong> → WebP or PNG. Never JPEG.', '<strong>Is it animated?</strong> → WebP, or ideally a real video file, which is smaller still.']),
 ('p', 'And whatever you choose, check the dimensions first. That is where the bytes actually are.'),
 ],
 },
 {
 'slug': 'why-is-my-json-invalid',
 'icon': '{ }',
 'nav_title': 'Why is my JSON invalid',
 'headline': 'Why is my JSON invalid when it looks perfectly fine?',
 'title': 'Why Is My JSON Invalid? The Four Mistakes That Cause Almost Every Error',
 'standfirst': 'Four small differences between JSON and JavaScript account for the overwhelming majority of parse failures, and error messages point at the wrong line.',
 'description': 'Trailing commas, single quotes, unquoted keys and unescaped characters cause almost every JSON parse error. How to spot each one, and why the reported line is often wrong.',
 'published': '2026-02-25',
 'keywords': ['why is my json invalid', 'json unexpected token', 'json trailing comma error', 'json parse error line', 'json vs javascript object'],
 'related_tools': [('json-formatter', 'JSON Formatter'), ('csv-to-json', 'CSV to JSON'), ('regex-tester', 'Regex Tester')],
 'body': [
 ('p', 'JSON looks like a JavaScript object, which is exactly why it trips people up. It is a <em>subset</em> of JavaScript object syntax, and the things it leaves out are precisely the conveniences you are used to.'),
 ('p', 'Four mistakes cause the overwhelming majority of parse failures. Here they are, in descending order of how often they catch people.'),
 ('h2', '1. The trailing comma'),
 ('p', 'This is the most common by a wide margin, because modern JavaScript permits it and most editors will not flag it.'),
 ('quote', 'A comma after the final item in an object or array is valid JavaScript. It is not valid JSON. The specification permits commas only <em>between</em> elements.'),
 ('p', 'It usually appears when you delete the last property from a hand-edited config file and forget to remove the comma from the line above it. The error message you get, typically something about an unexpected token, points at the closing brace, not the comma.'),
 ('h2', '2. Single quotes'),
 ('p', 'JavaScript treats <code>\'value\'</code> and <code>"value"</code> as equivalent. JSON does not. Every string in JSON must use double quotes, without exception. This catches people constantly when copying object literals out of JavaScript source.'),
 ('p', 'The same applies to keys, which brings us to the third mistake.'),
 ('h2', '3. Unquoted keys'),
 ('p', 'In JavaScript you can write <code>{name: "Ada"}</code>. In JSON the key must be quoted: <code>{"name": "Ada"}</code>. Always, even when the key is a simple identifier with no spaces or special characters.'),
 ('p', 'This is the difference that most often reveals someone has pasted a JavaScript object where JSON was expected. If your data came out of a <code>console.log</code>, it is almost certainly a JavaScript object literal rather than JSON, and will need both the quotes fixed and any trailing commas removed.'),
 ('h2', '4. Unescaped characters inside strings'),
 ('p', 'A literal newline inside a JSON string is invalid, it must be written as <code>\\n</code>. The same applies to tabs, and to double quotes and backslashes appearing inside a string.'),
 ('p', 'This one is nastier than the others because the offending character is often invisible. Text pasted from a word processor frequently contains non-breaking spaces or smart quotes; text pasted from a terminal may contain control characters. The file looks correct and will not parse.'),
 ('callout', 'A quick diagnostic', 'If your JSON fails and you cannot see why, paste it into a formatter that reports line and column. If the reported column points at a character that appears to be an ordinary space, it is probably a non-breaking space or another invisible character.'),
 ('tool', 'json-formatter', 'JSON Formatter', 'Reports the exact line and column where parsing failed, then beautifies or minifies once the JSON is valid. Everything is parsed locally, so you can safely paste an API response containing real credentials or customer data.'),
 ('h2', 'Why the error points at the wrong line'),
 ('p', 'This deserves its own section because it wastes so much time.'),
 ('p', 'A parser reports where it <em>gave up</em>, not where you made the mistake. Those are frequently different places. If you forget a comma at the end of line 8, the parser reads line 8 successfully, moves to line 9, and only then discovers it was expecting a comma or a closing brace. It reports an error on line 9.'),
 ('p', 'So when a JSON error points at a line that looks perfectly fine, <strong>check the line above it.</strong> That habit alone will resolve a large fraction of these.'),
 ('h2', 'Things JSON does not have'),
 ('p', 'Beyond the four mistakes, a set of things people reasonably expect and do not get:'),
 ('ul', ['<strong>Comments.</strong> Neither <code>//</code> nor <code>/* */</code>. This was a deliberate decision by Douglas Crockford, who removed them because people were using them to carry parsing directives.', '<strong>Undefined.</strong> There is <code>null</code>, and nothing else. A JavaScript property set to <code>undefined</code> simply vanishes when serialised.', '<strong>NaN and Infinity.</strong> Not representable. <code>JSON.stringify</code> turns them into <code>null</code>, silently.', '<strong>Dates.</strong> No date type. Dates become ISO 8601 strings and must be parsed back manually, a round trip does not restore a Date object.', '<strong>Trailing decimals.</strong> <code>1.</code> and <code>.5</code> are both invalid; write <code>1.0</code> and <code>0.5</code>.']),
 ('h2', 'The variants that fix some of this'),
 ('p', 'Several relaxed dialects exist, and it is worth knowing they are <em>not</em> JSON:'),
 ('table', ['Format', 'Adds', 'Where you will meet it'], [['JSONC', 'Comments', 'VS Code settings files'], ['JSON5', 'Comments, trailing commas, unquoted keys, single quotes', 'Config files'], ['NDJSON', 'One JSON object per line', 'Log streams, bulk APIs'], ['JSON Lines', 'Same as NDJSON', 'Data pipelines']]),
 ('p', 'If a file with comments parses fine in VS Code but fails in your program, this is why: it is JSONC, and a standard JSON parser will reject it.'),
 ('h2', 'One security note'),
 ('p', 'If you are parsing JSON from an untrusted source, use <code>JSON.parse</code> and never <code>eval</code>. This should go without saying, but code that predates <code>JSON.parse</code> being universally available still circulates, and <code>eval</code> on attacker-controlled input executes arbitrary code.'),
 ('h2', 'How to debug invalid JSON systematically'),
 ('p', 'When a parser rejects your JSON, the error message almost always names a line and column, and that pointer is the fastest route to the fix. Start there rather than scanning the whole document. The parser reports the point where it first got confused, which is usually at or just after the real mistake, a missing comma on the previous line, for instance, is often flagged at the start of the next one. Reading the character immediately before the reported position resolves a large share of errors on its own.'),
 ('p', 'For anything larger than a few lines, paste the document into a formatter that validates as it pretty-prints. Formatting collapses the two most common problems into plain sight: mismatched brackets become obvious once the structure is indented, and a value that is not properly quoted stands out against its neighbours. If the JSON is genuinely large, validate progressively, comment out or remove sections until it parses, then reintroduce them until it breaks again, which isolates the offending block quickly.'),
 ('p', 'Also be aware that <code>JSON.parse</code> will happily parse deeply nested structures until it exhausts the stack. If you are accepting JSON from users, cap the payload size before parsing rather than after.'),
 ],
 },
 {
 'slug': 'cron-day-of-week-trap',
 'icon': '⏰',
 'nav_title': 'The cron day-of-week trap',
 'headline': 'The cron mistake that runs your job far more often than you intended',
 'title': 'Cron Day-of-Month and Day-of-Week: The OR Trap Explained',
 'standfirst': 'When both day fields are restricted, cron runs the job if <em>either</em> matches, not both. This is not a bug, and it surprises nearly everyone.',
 'description': "Why '0 0 1 * 1' runs on the 1st of the month AND every Monday, plus the DST and overlapping-job problems that bite cron users in production.",
 'published': '2026-03-04',
 'keywords': ['cron day of week day of month both', 'cron expression explained', 'cron runs too often', 'crontab or condition', 'cron dst problem'],
 'related_tools': [('cron-expression-builder', 'Cron Expression Builder'), ('time-zone-converter', 'Time Zone Converter'), ('timestamp-converter', 'Timestamp Converter')],
 'body': [
 ('p', 'Consider this crontab line, intended to run a job on the first Monday of each month:'),
 ('quote', '<code>0 0 1 * 1</code>'),
 ('p', 'It does not do that. It runs at midnight on the 1st of every month, <strong>and also every Monday</strong>. In a typical month that is around five runs instead of one.'),
 ('p', 'This is documented behaviour, not a bug, and it catches almost everyone the first time.'),
 ('h2', 'The rule'),
 ('p', 'Cron has five fields: minute, hour, day-of-month, month, day-of-week. Four of them combine with AND, exactly as you would expect. The two day fields are the exception.'),
 ('ul', ['If <strong>both</strong> day-of-month and day-of-week are restricted (neither is <code>*</code>), cron runs the job when <strong>either</strong> matches.', 'If <strong>only one</strong> is restricted, only that one applies.', 'If <strong>neither</strong> is restricted, the job runs every day.']),
 ('p', 'The historical reason is that the original Unix cron was written to make schedules like "the 1st and the 15th, and also every Friday" expressible in a single line. It is a deliberate design choice that has confused people for over four decades.'),
 ('callout', 'There is no way to express AND', 'Standard cron simply cannot express "the first Monday of the month". You must schedule it for every Monday and put a date check inside the job itself, or use a scheduler that supports richer expressions.'),
 ('h2', 'The workaround'),
 ('p', 'Schedule the broader condition in cron and narrow it in the job. For the first Monday:'),
 ('ol', ['Schedule for every Monday: <code>0 0 * * 1</code>', 'At the top of the script, check whether the day of the month is 7 or less.', 'Exit early if it is not.']),
 ('p', 'This is slightly inelegant and completely reliable. Some cron implementations, notably Quartz and several cloud schedulers, support a <code>#</code> syntax for this (<code>MON#1</code> meaning the first Monday), but standard Unix cron does not.'),
 ('tool', 'cron-expression-builder', 'Cron Expression Builder', 'Explains any expression in plain English, calculates the next five run times from your system clock, and explicitly flags the OR condition when both day fields are restricted.'),
 ('h2', 'Reading the rest of the syntax'),
 ('table', ['Symbol', 'Meaning', 'Example'], [['<code>*</code>', 'Every value', '<code>* * * * *</code>: every minute'], ['<code>,</code>', 'A list', '<code>0 9,17 * * *</code>: 9am and 5pm'], ['<code>-</code>', 'A range', '<code>0 9 * * 1-5</code>: 9am on weekdays'], ['<code>/</code>', 'A step', '<code>*/15 * * * *</code>: every 15 minutes']]),
 ('p', 'Day-of-week runs 0 to 6 with Sunday as 0. Some implementations also accept 7 for Sunday, which is a portability hazard worth avoiding. Month is 1 to 12, and hour is 0 to 23, there is no 24.'),
 ('h2', 'The daylight saving problem'),
 ('p', "Cron uses the server's local timezone, and this causes two distinct failures twice a year."),
 ('p', '<strong>In spring</strong>, when clocks jump forward, an hour simply does not exist. A job scheduled for 02:30 in a timezone that skips from 02:00 to 03:00 does not run at all that day. Some cron implementations compensate by running it immediately after the jump; others do not. The behaviour is not consistent across systems.'),
 ('p', '<strong>In autumn</strong>, when clocks go back, an hour repeats. A job scheduled for 01:30 may run twice. If that job charges customers, sends emails or processes a queue non-idempotently, running it twice is a real problem.'),
 ('p', 'The fix is straightforward: <strong>avoid scheduling anything between 01:00 and 03:00</strong>, or set the server to UTC and do timezone conversion inside the application. Most production systems do the latter, and it is the more robust answer.'),
 ('h2', 'Overlapping runs'),
 ('p', 'Cron does not know or care whether the previous run has finished. A job scheduled every minute that takes ninety seconds will start a second copy before the first completes, then a third, and so on until the machine runs out of memory.'),
 ('p', 'This is one of the most common ways a cron job takes down a server, and it usually happens long after deployment, the job was fast when it was written and got slower as the data grew.'),
 ('p', 'Guard against it with a lockfile. The <code>flock</code> utility does this in one line and is available on essentially every Linux system: wrap the command so a second instance simply exits rather than piling up.'),
 ('h2', 'Three more things that bite'),
 ('ul', ['<strong>The environment is minimal.</strong> Cron does not load your shell profile, so <code>PATH</code> is short and your usual environment variables are absent. A script that works interactively and fails under cron is nearly always this. Use absolute paths.', '<strong>Output goes to email.</strong> Anything a job writes to stdout or stderr is mailed to the crontab owner. If no mail system is configured, that output vanishes silently, which is why a failing cron job can be invisible for months. Redirect to a log file.', '<strong>The percent sign is special.</strong> In a crontab, <code>%</code> is translated to a newline. This breaks <code>date</code> format strings in particular, and must be escaped as <code>\\%</code>.']),
 ('h2', 'When not to use cron'),
 ('p', 'Cron is excellent for simple, periodic, independent tasks on a single machine. It is a poor fit for anything with dependencies between jobs, anything needing retries on failure, anything requiring visibility into whether a run succeeded, and anything that must run exactly once across a fleet of servers.'),
 ('h2', 'How to write cron schedules you can trust'),
 ('p', 'The safest habit with cron is to change one field at a time and read the whole expression back in plain English before you save it. Cron\'s five fields, minute, hour, day-of-month, month, day-of-week, are terse, and a single misplaced value can turn "every Monday at 9" into "every day at 9" without any visible error. Because a wrong schedule usually fails silently, running too often or not at all rather than throwing an error, the mistake is often discovered only when something important did not happen.'),
 ('p', 'Two rules prevent most disasters. First, avoid setting both day-of-month and day-of-week unless you genuinely understand that cron treats them as OR, not AND, the combination runs on either match, not both. Second, remember that both 0 and 7 mean Sunday, so a range like 1-7 covers the whole week with Sunday represented twice. When in doubt, build the expression with a tool that shows the next few run times in real dates, so you can confirm the schedule does what you meant before it goes live.'),
 ('p', 'If you find yourself building retry logic and alerting into cron jobs, that is the signal to move to a real scheduler. But for "rotate the logs at 3am", cron remains exactly the right tool, and has been for fifty years.'),
 ],
 },
 {
 'slug': 'what-a-checksum-actually-proves',
 'icon': '🔍',
 'nav_title': 'What a checksum proves',
 'headline': 'What does a matching checksum actually prove?',
 'title': "What a Matching Checksum Actually Proves (And What It Doesn't)",
 'standfirst': 'It reliably catches corruption. It proves considerably less about tampering than most people assume, and the reason is worth understanding.',
 'description': 'Why verifying a download against a published SHA-256 catches corruption but not a compromised server, and what signed hashes add that bare checksums cannot.',
 'published': '2026-03-11',
 'keywords': ['what does checksum prove', 'sha256 verify download', 'is md5 still safe', 'checksum vs signature', 'verify iso download'],
 'related_tools': [('hash-comparison', 'Hash Comparison'), ('hash-generator', 'Hash Generator'), ('encryption-tool', 'Encryption Tool')],
 'body': [
 ('p', 'You download a Linux ISO. The page lists a SHA-256 checksum. You compute the hash of your download, it matches, and you feel reassured.'),
 ('p', 'You should, but about a narrower thing than you probably think. <strong>A matching checksum proves your copy is byte-for-byte identical to the file the hash was computed from. It does not, on its own, prove that file was the one the project intended to publish.</strong>'),
 ('h2', 'What it genuinely proves'),
 ('p', 'A cryptographic hash maps any input to a fixed-size digest such that the same input always produces the same output, and any change, even a single flipped bit, produces a completely different output.'),
 ('p', 'That makes checksums excellent at catching:'),
 ('ul', ['<strong>Truncated downloads</strong>, where the connection dropped partway.', '<strong>Bit rot</strong> on storage media.', '<strong>Transmission errors</strong> that slipped past lower-level error correction.', '<strong>Accidentally grabbing the wrong file</strong> or an outdated version.']),
 ('p', 'These are the everyday cases, they are real, and verification is genuinely worth doing for them. A 4GB ISO that fails to boot after a two-hour install is a bad afternoon that a thirty-second hash check would have prevented.'),
 ('h2', 'The gap'),
 ('p', 'Now consider an attacker who has compromised the download server. They replace the ISO with a backdoored version.'),
 ('p', 'Can they also replace the checksum on the download page? Almost certainly yes, it is on the same server they just compromised. You would then compute the hash of the malicious file, compare it against the malicious hash, get a match, and conclude everything is fine.'),
 ('callout', 'The core limitation', 'A checksum published in the same place as the file it describes provides no protection against anyone who can modify both. It defends against accidents, not adversaries.'),
 ('p', 'This is not a hypothetical concern. Compromised mirrors and poisoned download pages have been used in real supply-chain attacks against widely used software.'),
 ('h2', 'What closes the gap'),
 ('p', 'Three things, in increasing order of strength:'),
 ('ol', ["<strong>A different channel.</strong> If the hash is published somewhere the attacker would also have to compromise separately, a different domain, the project's social account, a package manager's metadata, a match becomes meaningfully more informative.", "<strong>A cryptographic signature.</strong> Serious projects publish a signed hash file (usually GPG). Verifying the signature proves the hash came from someone holding the project's private key, which the server compromise alone does not grant.", "<strong>A pre-established trust anchor.</strong> The signature only helps if you obtained the project's public key through a trustworthy path, from a keyserver you verified previously, from your distribution's keyring, or in person. Downloading the key from the same compromised page proves nothing."]),
 ('p', 'This is why the instruction is usually "verify the signature on the checksum file" rather than "check the checksum". The extra step is the one doing the security work.'),
 ('tool', 'hash-comparison', 'Hash Comparison', 'Hash a local file and compare it against a published checksum, or compare two hashes directly. Uses constant-time comparison and detects the algorithm from digest length. The file is read in your browser and never uploaded.'),
 ('h2', 'Which algorithm, and why MD5 is finished'),
 ('p', 'You will still encounter MD5 and SHA-1 checksums. Both are broken for collision resistance, meaning it is computationally feasible to construct two <em>different</em> files with the <em>same</em> digest.'),
 ('table', ['Algorithm', 'Digest length', 'Status', 'Use for'], [['MD5', '32 hex chars', 'Broken since 2004', 'Accidental corruption only'], ['SHA-1', '40 hex chars', 'Collision demonstrated 2017', 'Legacy compatibility only'], ['SHA-256', '64 hex chars', 'Secure', 'Default choice'], ['SHA-512', '128 hex chars', 'Secure', 'Where speed on 64-bit matters']]),
 ('p', 'The 2017 SHAttered attack produced two different PDF files with an identical SHA-1 hash. For MD5, collisions can be generated on a laptop in seconds. Neither should be relied on where an adversary is involved.'),
 ('p', "They remain adequate for detecting accidental corruption, which is why Git still uses SHA-1 for object identifiers, Git's threat model there is disk errors, not attackers, and it has been migrating to SHA-256 regardless."),
 ('h2', 'The distinction that matters'),
 ('p', 'Worth being precise about two different properties:'),
 ('ul', ['<strong>Collision resistance</strong>: hard to find <em>any</em> two inputs with the same hash. This is what MD5 and SHA-1 have lost.', '<strong>Preimage resistance</strong>: hard to find an input producing a <em>specific</em> target hash. MD5 and SHA-1 technically still hold here.']),
 ('p', 'For verifying a download, preimage resistance is arguably the relevant property, which is why an MD5 checksum is not quite as useless as it sounds. But there is no reason to accept the weaker guarantee when SHA-256 costs nothing extra.'),
 ('h2', 'And never for passwords'),
 ('p', 'One thing hashes are emphatically not for: storing passwords. SHA-256 is designed to be fast, and fast is precisely wrong here, modern hardware computes billions of SHA-256 hashes per second, so a stolen database of SHA-256 password hashes falls quickly.'),
 ('p', 'Password storage needs a deliberately slow, memory-hard, salted function: Argon2id, scrypt or bcrypt. Adding a salt to SHA-256 defeats rainbow tables but does nothing about the speed problem, which is the actual issue.'),
 ('h2', 'A practical routine'),
 ('ol', ['Download the file and the checksum file.', 'If a signature is published, verify it first, that is the step doing the real work.', 'Compute the hash of your download and compare.', 'If they differ, do not assume malice. Re-download first: truncation is far more common than attack.']),
 ('h2', 'What a checksum cannot tell you'),
 ('p', 'A matching checksum is powerful but narrow: it proves that the file you have is bit-for-bit identical to the one whose hash you were given. That is exactly what you want for detecting accidental corruption during a download or transfer, because even a single flipped bit produces a completely different hash. But it proves nothing about where that reference hash came from. If an attacker can replace both the file and the published checksum, the two will match perfectly while the file is malicious.'),
 ('p', 'This is why checksums for security-sensitive downloads are often accompanied by a cryptographic signature, which ties the hash to a verifiable identity, or published over a trusted channel separate from the file itself. It is also why the algorithm matters: older functions like MD5 and SHA-1 can be deliberately fooled into producing collisions and should not be relied on for security, while SHA-256 remains sound. A checksum verifies integrity against accident; it verifies authenticity only when you can trust the source of the hash.'),
 ('p', 'And if a project publishes only a bare MD5 with no signature, that tells you something about how much attention it pays to supply-chain security generally.'),
 ],
 },
 {
 'slug': 'why-stacked-discounts-never-add-up',
 'icon': '🏷️',
 'nav_title': 'Why stacked discounts never add up',
 'headline': 'Why 20% off plus another 20% off is not 40% off',
 'title': 'Why Stacked Discounts Never Add Up (And What They Really Save You)',
 'standfirst': 'Two 20% discounts give you 36% off, not 40%. The gap widens as the discounts grow, and the arithmetic is worth knowing before you shop a sale.',
 'description': 'Stacked discounts multiply rather than add. Here is the arithmetic, why order does not matter, and the reference-price rule that determines whether a sale is real.',
 'published': '2026-03-18',
 'keywords': ['stacked discounts calculator', '20% off plus 20% off', 'how to calculate double discount', 'percentage discount on discount', 'extra 20% off already reduced'],
 'related_tools': [('discount-calculator', 'Discount Calculator'), ('percentage-calculator', 'Percentage Calculator'), ('tip-calculator', 'Tip Calculator')],
 'body': [
 ('p', 'A jacket is £200. It is marked 20% off, and there is a promotion offering an extra 20% off sale items. Most people expect to pay £120.'),
 ('p', 'You will pay <strong>£128</strong>. The two discounts give you 36% off, not 40%.'),
 ('h2', 'The arithmetic'),
 ('p', 'Discounts apply sequentially, each to whatever is left after the previous one. They multiply rather than add.'),
 ('ol', ['£200 with 20% off → you pay 80% → <strong>£160</strong>', '£160 with a further 20% off → you pay 80% of £160 → <strong>£128</strong>', '£128 out of £200 means you paid 64%, so the effective discount is <strong>36%</strong>']),
 ('p', 'The shortcut is to multiply what you pay rather than what you save: 0.8 × 0.8 = 0.64. You pay 64%, so you save 36%.'),
 ('h2', 'The gap widens with bigger discounts'),
 ('table', ['Two discounts', 'Naive sum', 'Actual effective discount', 'Difference'], [['10% + 10%', '20%', '19%', '1 point'], ['20% + 20%', '40%', '36%', '4 points'], ['30% + 30%', '60%', '51%', '9 points'], ['50% + 50%', '100%', '75%', '25 points'], ['70% + 70%', '140%', '91%', '49 points']]),
 ('p', 'The bottom rows show why the intuition fails so badly at the extremes. Two 50% discounts obviously cannot make something free, you pay a quarter of the original price. And no combination of percentage discounts can ever reach 100%, because you are always taking a fraction of something that remains positive.'),
 ('h2', 'Order does not matter'),
 ('p', 'A question that comes up often: does it matter whether the 30% or the 10% is applied first?'),
 ('p', 'Mathematically, no. Multiplication is commutative, so 0.7 × 0.9 and 0.9 × 0.7 both give 0.63. You pay 63% either way.'),
 ('p', 'It <em>does</em> matter when a fixed-amount voucher is involved. £20 off applied before a 50% discount saves you £10 in the end; applied after, it saves the full £20. Retailers specify the order in their terms, and it is almost always the one less favourable to you, percentage discounts first, fixed vouchers last.'),
 ('tool', 'discount-calculator', 'Discount Calculator', 'Handles single and stacked discounts, works backwards from a sale price to the original, and shows the working so you can check it. Also applies tax after the discount, which is the standard order.'),
 ('h2', 'Where tax fits'),
 ('p', 'In nearly every jurisdiction, tax is calculated on the discounted price, not the original. That is the correct order and it works in your favour, a discount reduces the tax you pay along with the price.'),
 ('p', 'In countries where prices are displayed including tax, such as most of Europe, this is invisible to you: the shelf price already includes it and the discount comes off the total. In the US, where sales tax is added at the till, you will see it applied to the reduced amount.'),
 ('h2', 'The question worth asking about any sale'),
 ('p', 'All of this arithmetic is secondary to a more basic point: <strong>a discount is only meaningful relative to a price the item genuinely sold at.</strong>'),
 ('p', '"Was £200, now £100" tells you nothing if it never actually sold at £200. This practice is common enough that several jurisdictions regulate it directly. EU rules require that a displayed prior price be the lowest price charged in the preceding 30 days. The UK and Australia have broadly similar provisions.'),
 ('p', 'Enforcement is patchy, and the rules generally do not cover items that were briefly listed at a high price before going on permanent sale. The practical defence is to compare against what competitors charge rather than against the number on the label.'),
 ('callout', 'A useful habit', 'Before buying something in a sale, check the current price at two other retailers. That tells you far more than the percentage on the tag does.'),
 ('h2', 'Working backwards'),
 ('p', 'Sometimes you know the sale price and want the original. Divide rather than multiply: if something is 30% off and costs £70, the original was £70 ÷ 0.7 = £100.'),
 ('p', 'The common error is to add 30% to £70, giving £91. That is wrong, because the 30% was taken from the larger number, not the smaller one. This is the same asymmetry that makes a 50% rise and a 50% fall not cancel out.'),
 ('h2', 'The related trap: percentage rises and falls'),
 ('p', 'A price that rises 20% and then falls 20% does not return to where it started. It ends at 96% of the original, because the 20% fall is taken from the higher number.'),
 ('p', 'The same logic explains something that catches investors out: a portfolio that falls 50% needs to rise 100% to break even, not 50%. Losses require proportionally larger gains to recover, and the effect is severe at large percentages.'),
 ('h2', 'How to calculate stacked discounts correctly'),
 ('p', 'The reliable way to combine percentage discounts is to multiply the remaining fractions rather than adding the discounts. A 20% discount leaves you paying 80%, or 0.8 of the price; a further 10% off leaves 90%, or 0.9. Multiply those together, 0.8 times 0.9 equals 0.72, and you are paying 72% of the original, a combined discount of 28%, not the 30% that adding the two figures suggests. The order does not matter: 10% then 20% gives the same 0.72, because multiplication is commutative.'),
 ('p', 'The same logic explains why a discount followed by a tax does not cancel out, and why "an extra 50% off the sale price" is so much less than half off the original. Each percentage always applies to whatever is left after the previous one, never to the starting figure. Whenever you see stacked offers, convert each to the fraction you keep, multiply them, and subtract from one to get the true combined discount, or let a calculator do it so the marketing framing never misleads you.'),
 ('p', 'This is not a trick played on shoppers so much as a consequence of how percentages work, but retailers rarely rush to explain it, because "28% off" sounds weaker than "20% plus an extra 10%." Knowing the maths puts you back in control: whenever offers stack, work out the single equivalent discount before deciding whether a deal is as good as it looks. A few seconds of multiplication is often the difference between a genuine bargain and a clever bit of framing.'),
 ('p', 'None of this is complicated once you see it, but the intuition that percentages simply add is remarkably persistent, and retailers are aware of it.'),
 ],
 },
 {
 'slug': 'dice-notation-explained',
 'icon': '🎲',
 'nav_title': 'Dice notation explained',
 'headline': 'What does 4d6kh3 mean? Dice notation explained',
 'title': 'Dice Notation Explained: 3d6+2, 4d6kh3, Advantage and Why It Matters',
 'standfirst': 'The compact grammar behind every tabletop game, plus the probability difference between rolling one d20 and rolling three d6.',
 'description': 'How to read dice notation like 3d6+2 and 4d6kh3, what keep-highest does to your averages, and why 3d6 behaves completely differently from 1d20.',
 'published': '2026-03-25',
 'keywords': ['what does 4d6kh3 mean', 'dice notation explained', '3d6 vs 1d20 probability', 'dnd ability score rolling', 'advantage disadvantage probability'],
 'related_tools': [('dice-roller', 'Dice Roller'), ('random-number-generator', 'Random Number Generator'), ('random-picker', 'Random Picker')],
 'body': [
 ('p', 'Dice notation is one of those conventions that is completely opaque until someone explains it, then immediately obvious. The basic form is <code>NdS</code>: roll N dice with S sides each and add them up.'),
 ('p', '<code>3d6</code> means three six-sided dice, giving a result between 3 and 18. <code>1d20</code> means one twenty-sided die. <code>2d10+5</code> means two ten-sided dice plus five.'),
 ('h2', 'The full grammar'),
 ('table', ['Notation', 'Meaning', 'Range'], [['<code>1d6</code>', 'One six-sided die', '1–6'], ['<code>3d6</code>', 'Three d6, summed', '3–18'], ['<code>3d6+2</code>', 'Three d6, plus 2', '5–20'], ['<code>1d20-1</code>', 'One d20, minus 1', '0–19'], ['<code>4d6kh3</code>', 'Four d6, keep the highest 3', '3–18'], ['<code>2d20kl1</code>', 'Two d20, keep the lowest 1', '1–20'], ['<code>d%</code>', 'Percentile, usually d100', '1–100']]),
 ('p', 'The <code>kh</code> and <code>kl</code> suffixes mean keep-highest and keep-lowest. They are where the notation stops being obvious, and they exist because rolling extra dice and discarding some is an extremely common mechanic.'),
 ('h2', 'Why 4d6kh3 exists'),
 ('p', 'This is the standard method for generating Dungeons &amp; Dragons ability scores: roll four six-sided dice, discard the lowest, sum the remaining three.'),
 ('p', 'The effect on the distribution is substantial. Plain <code>3d6</code> averages 10.5. <code>4d6kh3</code> averages about <strong>12.24</strong>: nearly two points higher, and shifts the whole curve upward. It also makes very low scores much rarer: the chance of rolling a 3 drops from 1 in 216 to 1 in 1,296.'),
 ('p', 'The design intent is to produce characters who are above average without eliminating the possibility of a weak score entirely. It is a neat piece of probability design.'),
 ('h2', 'Advantage and disadvantage'),
 ('p', 'Fifth edition D&amp;D introduced a mechanic that is just <code>2d20kh1</code> and <code>2d20kl1</code> under different names: roll two d20 and take the higher (advantage) or the lower (disadvantage).'),
 ('p', 'The effect is larger than most players intuit. Advantage adds roughly <strong>+3.3 to your average roll</strong>, but the benefit is not uniform, it is largest when you need a middling result and smallest at the extremes.'),
 ('table', ['Target number', 'Normal chance', 'With advantage', 'Improvement'], [['Need 5+', '80%', '96%', '+16 points'], ['Need 11+', '50%', '75%', '+25 points'], ['Need 15+', '30%', '51%', '+21 points'], ['Need 20', '5%', '9.75%', '+4.75 points']]),
 ('p', 'The peak is at exactly 50/50, where advantage is worth a full 25 percentage points. That is an enormous swing for a mechanic that costs nothing to describe.'),
 ('tool', 'dice-roller', 'Dice Roller', 'Supports the full notation including keep-highest, keep-lowest, modifiers, exploding dice and advantage. Uses crypto.getRandomValues() with rejection sampling, so every face is exactly equally likely, no modulo bias.'),
 ('h2', 'The bit that actually matters: flat versus bell curve'),
 ('p', 'This is the most important idea in dice design, and it explains why different games feel so different to play.'),
 ('p', '<strong>A single die is flat.</strong> On a d20, every result from 1 to 20 is equally likely, exactly 5% each. There is no "typical" roll. A 1 is as likely as an 11.'),
 ('p', '<strong>Multiple dice form a bell curve.</strong> On 3d6, the possible results run from 3 to 18, but they are wildly unequal. A 10 or 11 comes up about 12.5% of the time each. A 3 or an 18 comes up 0.46% of the time, once in 216 rolls.'),
 ('quote', 'There is only one way to roll 3 on 3d6 (1-1-1), but twenty-seven ways to roll 10. That ratio is the entire difference between the two systems.'),
 ('p', 'The design consequence is direct. A d20 system is swingy: a skilled character fails routinely and an unskilled one occasionally triumphs, which makes every roll dramatic. A 3d6 system is predictable: results cluster near the average, so competence reliably wins and modifiers matter enormously.'),
 ('p', 'Neither is better. GURPS uses 3d6 deliberately, because it wants a simulation where an expert rarely fumbles. D&amp;D uses d20 deliberately, because it wants the possibility of the improbable in every scene.'),
 ('h2', 'Exploding dice'),
 ('p', 'Some systems let a maximum roll trigger another roll, added to the total. Roll a 6 on a d6, roll again and add, and if that is also a 6, keep going.'),
 ('p', 'This makes the range technically unbounded and creates a long thin tail of very high results. The average of an exploding d6 rises from 3.5 to 4.2, but the more interesting effect is on the shape: rare, memorable, enormous results become possible from a small die.'),
 ('h2', 'Why the randomness source matters here too'),
 ('p', 'A physical die is fair enough for most purposes, though cheap dice are measurably biased, casino dice are machined to much tighter tolerances precisely because small imperfections in weight distribution shift the odds.'),
 ('p', "A digital roller has a different problem. Most use <code>Math.random()</code>, which is a predictable pseudo-random generator, and many then map the result into range with a modulo operation, which introduces a small systematic bias toward the lower faces whenever the die size does not divide evenly into the generator's output space."),
 ('h2', 'Reading more complex dice expressions'),
 ('p', 'Once the basic NdX form is familiar, N dice with X sides each, the modifiers follow a consistent grammar. A trailing "+K" or "-K" adds or subtracts a flat number after rolling, so 2d6+3 means roll two six-sided dice and add three. The "kh" and "kl" suffixes mean "keep highest" and "keep lowest": 4d6kh3, common in tabletop character creation, rolls four dice and keeps the best three, which nudges results upward. Its opposite, 2d20kl1, rolls two twenty-sided dice and keeps the lower, the mechanic many games call disadvantage.'),
 ('p', 'These notations exist because they compactly describe probability distributions, not just totals. Rolling 3d6 is not the same as rolling 1d18 even though both can total between 3 and 18: the three-dice version clusters heavily around 10 and 11 and almost never hits the extremes, because there are many more ways to make a middle total than an extreme one. Understanding that difference is the whole point of dice notation, it lets game designers and players reason precisely about how likely each outcome really is, rather than just its range.'),
 ('p', 'For a casual game this is irrelevant. For anything where the outcome matters, it is worth knowing that a properly implemented roller uses a cryptographic source and rejection sampling, which removes both problems entirely.'),
 ],
 },
]
