# ============================================
# 123MiniApps.online, Blog articles: Phase 1 Batch 1
# One long-form article per new premium tool.
# Consumed by build-blog.py via POST_MODULES.
# ============================================

POSTS = [
 {
  "slug": "what-is-binary-code-text-to-binary-explained",
  "icon": "🔢",
  "nav_title": "Binary code explained",
  "headline": "What Is Binary Code? How to Convert Text to Binary and Back",
  "title": "Binary Code Explained: Convert Text to Binary and Back | 123MiniApps",
  "standfirst": "How computers turn every letter into ones and zeros, how to read a byte, and how to convert text to binary and binary to text without getting the bits wrong.",
  "description": "What binary code is, how text becomes ones and zeros, how to read an 8-bit byte, and how to convert text to binary and back, with a free in-browser translator.",
  "published": "2026-09-09",
  "keywords": ["binary code", "text to binary", "binary to text", "what is binary", "binary translator", "how to read binary", "ascii binary"],
  "related_tools": [("binary-code-translator", "Binary Code Translator"), ("number-base-converter", "Number Base Converter"), ("text-to-ascii", "Text to ASCII"), ("base64-encoder-decoder", "Base64 Encoder / Decoder")],
  "body": [
   ("p", "Binary code is the language computers actually think in: every character you type, every pixel on this screen and every file on your disk is, at the lowest level, a pattern of ones and zeros. Converting text to binary makes that hidden layer visible, and it is far simpler than it looks once you know the two ideas behind it. This guide explains what binary is, how a letter becomes a byte, and how to convert text to binary and back reliably. You can follow along with the free <a href=\"../tools/binary-code-translator.html\">Binary Code Translator</a>, which runs entirely in your browser."),
   ("h2", "Why computers use binary"),
   ("p", "A computer is built from billions of tiny switches called transistors, and a switch has exactly two stable states: on or off. Binary, the base-2 number system, maps perfectly onto that reality, one digit for on, zero for off. Everything else is built on top. A single binary digit is called a bit, and eight bits grouped together make a byte. That grouping is not arbitrary: eight bits can represent 256 different values (2 to the power of 8), which was historically enough to cover every letter, digit and punctuation mark in English with room to spare."),
   ("p", "So when people say a computer stores your text as ones and zeros, what they mean precisely is that each character is stored as a number, and that number is stored as a byte of eight bits. The job of a binary translator is simply to make that chain, character to number to bits, visible in both directions."),
   ("h2", "From a letter to a number: character codes"),
   ("p", "Before text can become binary, each character needs a number. That mapping is defined by a character set. The oldest and most fundamental is ASCII, which assigns the numbers 0 to 127 to English letters, digits, punctuation and a few control codes. In ASCII, capital A is 65, lowercase a is 97, the digit 0 is 48, and a space is 32. These are not random: the codes were arranged so that sorting by number sorts roughly alphabetically, and so that switching between upper and lower case flips a single bit."),
   ("p", "You can see these numbers directly with the <a href=\"../tools/text-to-ascii.html\">Text to ASCII</a> tool. Once you have the number, the second step, turning it into binary, is pure arithmetic."),
   ("h2", "From a number to binary: reading a byte"),
   ("p", "Binary is a place-value system just like the decimal you use every day, except each place is worth twice the one to its right instead of ten times. In an 8-bit byte the places are worth, from left to right, 128, 64, 32, 16, 8, 4, 2 and 1. To read a byte, add up the place values wherever there is a 1."),
   ("p", "Take the letter A, code 65. In binary that is 01000001. Reading the ones: there is a 1 in the 64 place and a 1 in the 1 place, and 64 plus 1 is 65. That is the whole trick. Lowercase a, code 97, is 01100001, which is 64 plus 32 plus 1. Notice that A and a differ by exactly one bit, the 32 place, which is the single bit that controls letter case in ASCII."),
   ("table", ["Character", "ASCII code", "Binary (8-bit)"], [["A", "65", "01000001"], ["a", "97", "01100001"], ["Z", "90", "01011010"], ["0", "48", "00110000"], ["space", "32", "00100000"], ["!", "33", "00100001"]]),
   ("p", "Every printable character follows the same pattern. To convert a whole word, you convert each character in turn and write the bytes side by side, usually separated by a space so they are easy to read."),
   ("h2", "Converting text to binary, step by step"),
   ("p", "To convert the word Hi to binary by hand: H is code 72, which is 01001000; i is code 105, which is 01101001. So Hi becomes 01001000 01101001. That is exactly what the translator produces, and doing it once by hand is the fastest way to convince yourself the tool is not magic, just arithmetic done quickly."),
   ("tool", "binary-code-translator", "Binary Code Translator", "Type text to see its binary instantly, or paste binary to decode it. Full UTF-8 support, plus decimal and hexadecimal output, all in your browser."),
   ("h2", "Converting binary back to text"),
   ("p", "Decoding is the same process in reverse, and the one rule that matters is grouping. Because each character is eight bits, you split the binary into groups of eight, read each group back to its number, and look the number up in the character set. That is why a valid binary string must have a length that is a multiple of eight: if it does not, a byte is incomplete and cannot be decoded. If a translator ever refuses your input, count the digits, a stray or missing bit is almost always the cause."),
   ("h2", "Beyond English: UTF-8, emoji and accents"),
   ("p", "Plain ASCII only reaches 127, which covers English but not accented letters, other alphabets, or emoji. The modern solution is Unicode, encoded as UTF-8. UTF-8 keeps the original ASCII codes unchanged for English, but represents everything else using two, three or four bytes. An accented e or a smiling emoji is therefore several bytes long in binary, not one. This is why a good binary translator defaults to UTF-8: it handles the full range of characters people actually type, and still behaves identically to ASCII for plain English."),
   ("callout", "A quick sanity check", "If you convert a single emoji and get 32 bits (four bytes) rather than 8, nothing is broken, that is UTF-8 correctly using four bytes to encode a character outside the ASCII range."),
   ("h2", "Binary, decimal and hexadecimal"),
   ("p", "Binary is precise but long: one byte is eight digits, and a short sentence becomes a wall of ones and zeros. That is why programmers often view the same bytes in hexadecimal instead, where each byte is just two compact digits. Hex and binary line up perfectly because 16 is 2 to the power of 4, so one hex digit equals exactly four bits. The letter A, binary 01000001, is 41 in hex and 65 in decimal, three notations for one value. The translator shows all three at once so you can move between them, and the <a href=\"../tools/number-base-converter.html\">Number Base Converter</a> lets you explore any base directly."),
   ("h2", "Common questions"),
   ("p", "<strong>Is binary the same as machine code?</strong> Not quite. Binary is the number system; machine code is the specific binary instructions a processor runs. Both are ones and zeros, but converting text to binary gives you the data representation, not runnable code. <strong>Why is a byte eight bits?</strong> Historically because eight bits was the smallest group that could hold one character plus a little headroom, and the size stuck. <strong>Can I convert binary to text on my phone?</strong> Yes, the translator is a web page that runs in any browser, and because it works entirely on your device your text is never uploaded."),
   ("p", "Binary looks intimidating because it is long, not because it is complicated. Every character is a number, every number is a sum of powers of two, and every conversion is reversible. Keep the <a href=\"../tools/binary-code-translator.html\">Binary Code Translator</a> open while you experiment, and pair it with the <a href=\"../tools/text-to-ascii.html\">Text to ASCII</a> tool to see the character codes that sit in between."),
  ],
 },
 {
  "slug": "morse-code-explained-how-to-read-and-translate",
  "icon": "📡",
  "nav_title": "Morse code explained",
  "headline": "Morse Code Explained: How to Read, Write and Translate It",
  "title": "Morse Code Explained: Read, Write & Translate It | 123MiniApps",
  "standfirst": "The dots and dashes behind SOS, how the timing actually works, and how to translate text to Morse and back, with sound, in your browser.",
  "description": "How Morse code works: the alphabet of dots and dashes, the timing rules behind words per minute, how to read it, and a free translator with audio playback.",
  "published": "2026-09-09",
  "keywords": ["morse code", "morse code translator", "how to read morse code", "morse alphabet", "text to morse", "sos morse code", "morse code timing"],
  "related_tools": [("morse-code-translator", "Morse Code Translator"), ("text-to-speech", "Text to Speech"), ("binary-code-translator", "Binary Code Translator"), ("text-to-ascii", "Text to ASCII")],
  "body": [
   ("p", "Morse code has been carrying messages for nearly two centuries, from telegraph wires to distress calls at sea, and it still turns up today in aviation, amateur radio and the occasional puzzle. At its heart it is beautifully simple: every letter and number is a short pattern of dots and dashes. This guide explains the alphabet, the timing that makes it readable, and how to translate text to Morse and back. You can hear any message played aloud with the free <a href=\"../tools/morse-code-translator.html\">Morse Code Translator</a>."),
   ("h2", "What Morse code actually is"),
   ("p", "Morse code represents text as sequences of two symbols: the dot (a short signal) and the dash (a long one). Samuel Morse and Alfred Vail developed it in the 1830s and 1840s so that messages could travel down a telegraph wire as simple on-off pulses. Because it needs only a single channel that can be switched on and off, Morse can be sent as sound, light, a tapped finger or an electrical pulse, which is exactly why it has survived so long: any medium that can be turned on and off can carry it."),
   ("p", "The code was designed cleverly. The most common English letters were given the shortest patterns, so E, the most frequent letter, is a single dot, and T is a single dash. Rare letters like Q and Y get longer patterns. This frequency-based design made real messages faster to send than an evenly-sized code ever could."),
   ("h2", "The Morse alphabet"),
   ("p", "Here are the letters and digits. Read the dots as short and the dashes as long; the famous SOS, three dots, three dashes, three dots, appears at the end because it is the clearest example of all."),
   ("table", ["Letter", "Morse", "Letter", "Morse"], [["A", ".-", "N", "-."], ["B", "-...", "O", "---"], ["C", "-.-.", "S", "..."], ["E", ".", "T", "-"], ["H", "....", "U", "..-"], ["I", "..", "V", "...-"], ["K", "-.-", "W", ".--"], ["M", "--", "Z", "--.."]]),
   ("p", "Numbers follow a neat pattern of five symbols each: 1 is .---- , 5 is ..... , and 0 is ----- . Punctuation exists too, a full stop is .-.-.- , but letters and numbers cover almost everything you will ever need."),
   ("h2", "The part everyone forgets: timing"),
   ("p", "Knowing the patterns is only half of Morse. The other half is timing, because the gaps carry as much meaning as the marks. Everything is measured in one basic unit of time, and the rules are fixed: a dot is one unit, a dash is three units, the gap between symbols within a letter is one unit, the gap between letters is three units, and the gap between words is seven units. Get the spacing wrong and HELLO can dissolve into gibberish even if every individual dot and dash is correct."),
   ("p", "This is why written Morse uses spacing conventions: a single space between letters and a slash between words. So HI THERE is written .... .. / - .... . .-. . , and the translator uses exactly that format."),
   ("h2", "Words per minute: how fast is Morse?"),
   ("p", "Morse speed is measured in words per minute, and it is standardised using the reference word PARIS, which is exactly 50 units long including its spacing. At 15 words per minute you are sending 750 units every minute, so each unit lasts 80 milliseconds. Raise the speed and every dot, dash and gap shrinks proportionally. Experienced operators comfortably read 20 to 30 words per minute; contest operators go much faster. The translator lets you drag a speed slider so you can start slow and speed up as your ear adjusts."),
   ("tool", "morse-code-translator", "Morse Code Translator", "Convert text to Morse and back, then press play to hear it keyed at any speed while an on-screen light flashes in time. Everything runs in your browser."),
   ("h2", "How to read Morse by ear"),
   ("p", "Reading Morse aurally is a skill, not a lookup. The trick experienced operators use is to learn the sound of each letter as a rhythm rather than counting dots and dashes. E is a single tap; A is di-dah; S is di-di-dit. Beginners are often taught with the Koch method, which starts at full speed with just two characters and adds more as each is mastered, and the Farnsworth method, which keeps characters fast but stretches the gaps so your brain has time to recognise each one. Playing messages through the translator at a slow speed, then gradually raising it, mirrors that approach."),
   ("h2", "Why SOS became the distress signal"),
   ("p", "SOS, dot dot dot dash dash dash dot dot dot, was chosen as the international distress signal in the early 1900s precisely because it is unmistakable. It is usually sent as one continuous string with no letter gaps, giving a distinctive nine-symbol rhythm that stands out even through noise and interference. Contrary to popular belief it does not officially stand for save our souls or save our ship; those are later backronyms. It was picked for its clarity, not its meaning."),
   ("h2", "Where Morse is still used"),
   ("p", "Morse is no longer required for most maritime or aviation licensing, but it has not disappeared. Aviation navigation beacons still identify themselves in Morse, amateur radio operators use it because it punches through weak, noisy conditions where voice fails, and it remains a reliable fallback for emergency signalling with a light or a whistle when nothing else is available. It also endures as a hobby and a puzzle staple, which is where most people meet it today."),
   ("h2", "Common questions"),
   ("p", "<strong>How do I write a space between words?</strong> Use a forward slash surrounded by spaces, so the translator reads it as a word break. <strong>Is Morse code case sensitive?</strong> No, there is only one set of patterns, so uppercase and lowercase produce the same code. <strong>Can I play Morse as sound?</strong> Yes, the translator generates correctly timed tones and flashes a light in sync, so you can train your ear and eye together. <strong>Is my message private?</strong> Yes, the translation and audio run entirely in your browser and nothing is uploaded."),
   ("p", "Morse rewards a little practice more than almost any code, because once the rhythms click you can read them anywhere: a flashing light, a tapped table, a beeping tone. Start with the <a href=\"../tools/morse-code-translator.html\">Morse Code Translator</a> at a gentle speed, and when you want to hear text spoken instead, the <a href=\"../tools/text-to-speech.html\">Text to Speech</a> tool is one click away."),
  ],
 },
 {
  "slug": "online-stopwatch-lap-vs-split-times",
  "icon": "⏱️",
  "nav_title": "Stopwatch: laps vs splits",
  "headline": "How to Use an Online Stopwatch: Lap vs Split Times Explained",
  "title": "Online Stopwatch Guide: Lap vs Split Times | 123MiniApps",
  "standfirst": "What lap and split times really mean, when each one matters, and how to time workouts, study sessions and anything else accurately in your browser.",
  "description": "Lap time versus split time explained, how stopwatch precision works, and how to time workouts, rehearsals and study sessions with a free in-browser stopwatch.",
  "published": "2026-09-09",
  "keywords": ["online stopwatch", "lap time vs split time", "stopwatch with laps", "how to use a stopwatch", "split timer", "interval timing"],
  "related_tools": [("online-stopwatch", "Online Stopwatch"), ("countdown-timer", "Countdown Timer"), ("pomodoro-timer", "Pomodoro Timer"), ("meeting-cost-calculator", "Meeting Cost Calculator")],
  "body": [
   ("p", "A stopwatch seems like the simplest tool in the world, press start, press stop, but the moment you need to time more than one thing at once, two words start to matter: lap and split. Getting them straight is the difference between useful timing data and a single number you cannot do much with. This guide explains what lap and split times mean, when each is the one you want, and how to time real activities accurately with the free <a href=\"../tools/online-stopwatch.html\">Online Stopwatch</a>."),
   ("h2", "Lap time versus split time"),
   ("p", "The confusion comes from the fact that a stopwatch can report two different things each time you press the lap button, and different fields of use borrow the words differently. Here is the clear version. The split time (sometimes called the cumulative or total time) is the running clock measured from the very start. The lap time is how long the most recent segment took on its own, that is, the time since the previous press. If you start a stopwatch and press lap at 30 seconds and again at 70 seconds, your splits are 0:30 and 1:10, while your lap times are 0:30 and 0:40."),
   ("table", ["Press", "Split (total)", "Lap (segment)"], [["1st lap", "0:30", "0:30"], ["2nd lap", "1:10", "0:40"], ["3rd lap", "1:45", "0:35"]]),
   ("p", "A runner doing four laps of a track cares about lap times, they want to know if lap three slowed down. A swimmer or a project manager tracking total elapsed time cares about the split. A good stopwatch shows both side by side so you never have to subtract in your head, which is exactly what this one does."),
   ("h2", "When to use which"),
   ("p", "Reach for lap times when each segment is a comparable unit and you want to spot variation: interval training, lifting sets, repeated drills, timed rounds. Reach for split times when segments build toward a whole and you care about pace against a target: a long run broken into kilometres, stages of a recipe, sections of a presentation you are rehearsing against a time limit. Because the tool records both for every press, you can decide after the fact which number tells the story."),
   ("tool", "online-stopwatch", "Online Stopwatch", "Precise to a hundredth of a second, with a lap and split table, space-bar and L-key control, and one-click CSV export of every lap."),
   ("h2", "How stopwatch precision actually works"),
   ("p", "You might expect a stopwatch to count ticks, but counting is exactly what makes cheap timers drift. A well-built browser stopwatch instead reads the device's high-resolution clock and calculates the difference between the moment you started and now. That means pausing and resuming never accumulates error, and the elapsed time stays correct even if the tab is busy or briefly backgrounded. The display refreshes many times a second for a smooth readout, but the underlying time is measured, not tallied, which is why the hundredths of a second never stutter or fall behind."),
   ("h2", "Timing hands-free with the keyboard"),
   ("p", "When you are timing something physical, reaching for the mouse is slow and error-prone. Keyboard control fixes that: the space bar starts and stops, and the L key records a lap. You can rest a finger on the space bar while you rehearse a speech, or tap L at the end of each set without looking. This small feature is what turns a stopwatch from a toy into a genuinely useful measurement tool."),
   ("h2", "Getting your laps out: CSV export"),
   ("p", "A list of laps on screen is handy in the moment, but the value often comes later, charting your pace across a workout, comparing this week's intervals to last week's, or logging rehearsal times. Exporting your laps to a CSV file lets you open them in any spreadsheet and analyse them properly. Because everything runs locally, that export happens on your device with nothing uploaded, so timing a private training session or a confidential rehearsal stays entirely yours."),
   ("h2", "Practical timing tips"),
   ("ul", ["Start the clock a beat before the action and note it, reaction time on the start is your largest source of error.", "For intervals, press lap at the same reference point every time (the same line, the same rep) so lap times are comparable.", "Use split times when you have a target finish and want to know if you are ahead or behind partway through.", "Export and keep your laps, trends across sessions tell you far more than any single time."]),
   ("h2", "Stopwatch, countdown or Pomodoro?"),
   ("p", "A stopwatch counts up from zero and is right when you want to measure how long something takes. When you instead want to count down to a deadline, a boiling egg, a timed exam, a speaking slot, the <a href=\"../tools/countdown-timer.html\">Countdown Timer</a> is the better fit. And when the goal is focused work in fixed blocks with breaks, the <a href=\"../tools/pomodoro-timer.html\">Pomodoro Timer</a> structures the whole session for you. They are three views of time, up, down and in blocks, and the right one depends on the question you are asking."),
   ("h2", "Common questions"),
   ("p", "<strong>Does the stopwatch keep running if I switch tabs?</strong> Yes, because it measures against the system clock rather than counting in the foreground, elapsed time stays accurate. <strong>What is the difference between a lap and a split again?</strong> The lap is the length of one segment; the split is the total time since the start. This tool shows both for every lap. <strong>Can I use it on my phone?</strong> Yes, it works in any mobile browser, and you can tap the on-screen buttons instead of the keyboard. <strong>Is any data sent anywhere?</strong> No, timing and export run entirely on your device."),
   ("p", "Whether you are running intervals, rehearsing a talk or timing a recipe, the skill is not pressing start, it is reading the right number afterwards. Keep the <a href=\"../tools/online-stopwatch.html\">Online Stopwatch</a> open, watch your lap times for consistency and your splits for pace, and export the data when a single session becomes a habit worth tracking."),
  ],
 },
 {
  "slug": "how-to-calculate-gpa-weighted-cumulative",
  "icon": "🎓",
  "nav_title": "How to calculate GPA",
  "headline": "How to Calculate Your GPA: Weighted, Cumulative and by Scale",
  "title": "How to Calculate GPA: Weighted & Cumulative Explained | 123MiniApps",
  "standfirst": "Why GPA is a weighted average, how credit hours change the maths, the difference between 4.0, 4.3 and 5.0 scales, and how to work out your cumulative GPA.",
  "description": "How to calculate GPA step by step: the weighted average formula, how credit hours work, the 4.0, 4.3 and 5.0 scales, and cumulative GPA, with a free calculator.",
  "published": "2026-09-09",
  "keywords": ["how to calculate gpa", "gpa calculator", "weighted gpa", "cumulative gpa", "grade point average", "4.0 scale", "gpa formula"],
  "related_tools": [("gpa-calculator", "GPA Calculator"), ("percentage-calculator", "Percentage Calculator"), ("scientific-calculator", "Scientific Calculator"), ("discount-calculator", "Discount Calculator")],
  "body": [
   ("p", "Your grade point average is one number that summarises years of work, and yet most students are unsure exactly how it is calculated. The key thing to understand is that GPA is a weighted average, not a simple one: a top grade in a heavy course counts for far more than the same grade in a light one. This guide walks through the formula, the role of credit hours, the different grading scales, and how cumulative GPA builds up over time. You can check any of it with the free <a href=\"../tools/gpa-calculator.html\">GPA Calculator</a>."),
   ("h2", "Step one: turn letter grades into points"),
   ("p", "Every letter grade maps to a number of grade points. On the standard American 4.0 scale, an A is worth 4.0, a B is 3.0, a C is 2.0, a D is 1.0 and an F is 0.0, with plus and minus grades filling the gaps (an A- is 3.7, a B+ is 3.3, and so on). This mapping is the foundation of everything: before any averaging happens, each of your grades becomes a point value."),
   ("table", ["Grade", "Points", "Grade", "Points"], [["A / A+", "4.0", "C", "2.0"], ["A-", "3.7", "C-", "1.7"], ["B+", "3.3", "D+", "1.3"], ["B", "3.0", "D", "1.0"], ["B-", "2.7", "F", "0.0"]]),
   ("h2", "Step two: weight by credit hours"),
   ("p", "This is the step people miss. Courses are not equal, a four-credit core class represents far more work than a one-credit seminar, so it should influence your average more. GPA handles this by weighting each grade by its credit hours. For each course you multiply its grade points by its credits to get quality points, then you add up the quality points across every course and divide by the total number of credits. That division by total credits is what makes it a weighted average rather than a plain one."),
   ("p", "The formula in words: GPA equals total quality points divided by total credit hours, where quality points for a course equals grade points times credits."),
   ("h2", "A worked example"),
   ("p", "Suppose you take three courses: an A in a 3-credit class, a B+ in a 3-credit class, and an A- in a 4-credit class. Convert and weight each one: the A gives 4.0 times 3, which is 12.0 quality points; the B+ gives 3.3 times 3, which is 9.9; the A- gives 3.7 times 4, which is 14.8. Add the quality points: 12.0 plus 9.9 plus 14.8 is 36.7. Add the credits: 3 plus 3 plus 4 is 10. Divide: 36.7 divided by 10 is a GPA of 3.67."),
   ("p", "Notice that the A- in the four-credit course pulled real weight, more than either three-credit result, because it carried more credits. That is the whole point of weighting, and it is why two students with the same letter grades can end up with different GPAs if their course credits differ."),
   ("tool", "gpa-calculator", "GPA Calculator", "Add each course with its grade and credits and get your weighted GPA instantly, on the 4.0, 4.3 or 5.0 scale. Nothing is saved or uploaded."),
   ("h2", "Weighted GPA and the 5.0 scale"),
   ("p", "There is a second, separate meaning of weighted GPA that causes confusion. So far, weighted has meant weighted by credit hours, which every GPA is. But many high schools also use a weighted scale that awards extra points for harder courses: an A in a regular class is 4.0, but an A in an honours or Advanced Placement class might be 4.5 or 5.0. This rewards students for taking a tougher load and is why some high-school GPAs exceed 4.0. If your school does this, choose the 5.0 scale in the calculator so an A in an advanced course scores correctly."),
   ("h2", "The 4.3 scale and the A-plus question"),
   ("p", "Institutions also disagree on whether an A+ is worth more than an A. On the most common 4.0 scale, A and A+ are both capped at 4.0. On a 4.3 scale, an A+ is worth 4.3, which slightly rewards perfection. Neither is more correct; they are just different conventions, and your transcript follows your institution's choice. The calculator lets you pick the scale so the result matches your official record rather than a generic default."),
   ("h2", "Cumulative GPA: adding up over time"),
   ("p", "Your GPA for a single term is a semester GPA. Your cumulative GPA is the same calculation applied across every course you have ever taken: all quality points divided by all credit hours. It is not the average of your semester GPAs, that would be wrong, because it would ignore how many credits each term carried. A light term with a high GPA moves your cumulative figure less than a heavy term with the same GPA. The reliable way to track it is to keep adding every course to the same calculation, which is exactly how the tool builds a running total of credits and grade points."),
   ("callout", "Use it to plan, not just to record", "Because the maths is transparent, you can enter the grades you expect next term alongside your current courses to see where your GPA would land. It turns the calculator from a report card into a planning tool."),
   ("h2", "Common questions"),
   ("p", "<strong>Is cumulative GPA the average of my semester GPAs?</strong> No. It is total quality points over total credits across all terms, which correctly weights bigger terms more. <strong>Do pass or fail courses count?</strong> Usually not toward GPA, since they have no grade points; check your institution's policy and simply leave them out. <strong>Why is my weighted GPA above 4.0?</strong> Because a weighted scale adds points for honours or AP courses. <strong>Is my data private?</strong> Yes, everything is calculated in your browser and nothing is stored online."),
   ("p", "GPA feels mysterious only until you see the two moving parts: grades become points, and points are weighted by credits. Once that clicks, you can calculate, check and plan your average with confidence. Keep the <a href=\"../tools/gpa-calculator.html\">GPA Calculator</a> handy each term, and use the <a href=\"../tools/percentage-calculator.html\">Percentage Calculator</a> when you need to convert an individual grade to or from a percentage."),
  ],
 },
 {
  "slug": "how-to-calculate-sales-tax-and-vat",
  "icon": "🧾",
  "nav_title": "How to calculate sales tax",
  "headline": "How to Calculate Sales Tax and VAT (Adding and Reversing)",
  "title": "How to Calculate Sales Tax & VAT: Add and Reverse | 123MiniApps",
  "standfirst": "How to add tax to a price, the right way to work backwards and strip tax out of a total, and why subtracting the percentage gives the wrong answer.",
  "description": "How to calculate sales tax and VAT: add tax to a net price, and correctly reverse tax out of a gross total by dividing, not subtracting, with a free calculator.",
  "published": "2026-09-09",
  "keywords": ["how to calculate sales tax", "sales tax calculator", "how to calculate vat", "reverse vat", "add tax to price", "remove tax from total", "vat calculator"],
  "related_tools": [("sales-tax-calculator", "Sales Tax Calculator"), ("discount-calculator", "Discount Calculator"), ("percentage-calculator", "Percentage Calculator"), ("tip-calculator", "Tip Calculator")],
  "body": [
   ("p", "Sales tax and VAT look like simple percentages, and adding them is indeed easy. But the moment you need to work backwards, to find out how much tax is already baked into a total, most people reach for the wrong operation and get an answer that is close enough to look right and wrong enough to matter. This guide covers both directions properly: adding tax to a price, and correctly extracting tax from a gross total. You can check every figure with the free <a href=\"../tools/sales-tax-calculator.html\">Sales Tax Calculator</a>."),
   ("h2", "Adding tax: the easy direction"),
   ("p", "Start with the forward calculation, which is the one most people know. You have a net price, the amount before tax, and you want the total a customer pays. Convert the tax rate to a decimal by dividing by 100, multiply the price by it to get the tax, and add that to the price. A 100 item at an 8.5 percent rate: the tax is 100 times 0.085, which is 8.50, and the total is 108.50. Equivalently, you can multiply the price by 1.085 in one step to get the gross directly. Both routes give the same 108.50."),
   ("table", ["Step", "Calculation", "Result"], [["Net price", "given", "100.00"], ["Tax", "100 x 0.085", "8.50"], ["Gross total", "100 + 8.50", "108.50"]]),
   ("h2", "Reversing tax: the direction people get wrong"),
   ("p", "Now the hard direction, and the reason this article exists. You have a gross total that already includes tax, common with VAT, where displayed prices are tax-inclusive, and you want to know how much of it is tax. The instinct is to take the tax percentage of the total and subtract it. That is wrong, and here is why: the tax was originally calculated on the smaller net price, not on the larger gross total, so taking the percentage of the gross overstates it."),
   ("p", "The correct method is division. If a total of 108.50 includes 8.5 percent tax, the net price is the total divided by 1.085, which is exactly 100.00, and the tax is the difference, 8.50. Compare that with the wrong method: 8.5 percent of 108.50 is 9.22, which is too high by 72 cents on a small purchase, and the error grows with the amount. On a large invoice, that mistake becomes real money."),
   ("callout", "The rule to remember", "To add tax, multiply. To remove tax, divide by one plus the rate. Subtracting the percentage from a gross total always overstates the tax."),
   ("tool", "sales-tax-calculator", "Sales Tax Calculator", "Add tax to a net price or reverse it out of a gross total, and see the net, tax and gross figures at once, for any sales tax or VAT rate."),
   ("h2", "Why division works: the algebra in one line"),
   ("p", "If it helps to see why, here is the reasoning. The gross equals the net plus the tax, and the tax is the net times the rate, so gross equals net times one plus the rate. To recover the net you simply divide the gross by one plus the rate. For 8.5 percent, one plus the rate is 1.085, so net equals gross divided by 1.085. Everything else, the tax amount and the effective percentage, follows from that single step. The calculator's remove-tax mode does exactly this division for you."),
   ("h2", "Sales tax versus VAT: same maths, different habits"),
   ("p", "Sales tax, common in the United States, and value-added tax, common across Europe and much of the world, are calculated identically, both are a percentage added to a price. The practical difference is convention. US sales tax is usually shown added at the register, so the price on the shelf is the net and you add tax at checkout, the forward calculation. VAT is typically already included in the displayed price, so the figure you see is the gross and you often need to work backwards to find the tax, the reverse calculation. That is precisely when the divide-don't-subtract rule earns its keep."),
   ("h2", "Rounding and multiple items"),
   ("p", "Two small things trip people up in practice. First, rounding: tax is normally rounded to the nearest cent, and rounding each line item separately can differ by a penny from rounding the total, which is why receipts sometimes look a cent off. For everyday purposes, calculating tax on the total is fine. Second, mixed rates: if different items carry different tax rates, calculate each group separately and add the results, rather than applying a single blended rate, which only works if you compute the blend correctly. For a single rate across a basket, the calculator handles it in one step."),
   ("h2", "Everyday uses"),
   ("ul", ["Checking a receipt: enter the pre-tax total and your local rate to confirm the tax charged is correct.", "Pricing a product: work out the shelf price that yields the margin you want after tax.", "Reclaiming VAT: extract the tax portion from a tax-inclusive invoice for your records.", "Budgeting: see the true out-the-door cost of a purchase before you commit."]),
   ("h2", "Common questions"),
   ("p", "<strong>How do I find the tax in a total that already includes it?</strong> Divide the total by one plus the rate to get the net, then subtract to find the tax; the calculator's remove-tax mode does this. <strong>Is VAT calculated differently from sales tax?</strong> No, the arithmetic is the same; only the convention (added at the register versus included in the price) differs. <strong>Why is my reverse calculation different from just subtracting the percentage?</strong> Because the tax was applied to the net, not the gross, so you must divide rather than subtract. <strong>Are my figures private?</strong> Yes, the calculation runs entirely in your browser."),
   ("p", "Tax maths only has two moves, and now you have both: multiply to add it, divide to remove it. Keep the <a href=\"../tools/sales-tax-calculator.html\">Sales Tax Calculator</a> open for the next receipt or invoice, and pair it with the <a href=\"../tools/discount-calculator.html\">Discount Calculator</a> when a sale price and a tax both apply to the same purchase."),
  ],
 },
]
