# ============================================
# 123MiniApps.online, Blog articles: Phase 1 Batch 3
# One long-form article per new text-style tool.
# Consumed by build-blog.py via POST_MODULES.
# ============================================

POSTS = [
 {
  "slug": "bold-text-for-linkedin-and-instagram",
  "icon": "🅱️",
  "nav_title": "Bold text for social",
  "headline": "How to Make Bold Text for LinkedIn, Instagram and Anywhere Else",
  "title": "How to Make Bold Text for LinkedIn & Instagram | 123MiniApps",
  "standfirst": "There is no bold button on LinkedIn or Instagram, so the bold text you see is not formatting at all. Here is how it works and when to use it.",
  "description": "How to make bold text for LinkedIn, Instagram and other boxes with no bold button: how bold Unicode works, where it pastes, and when not to use it, with a free tool.",
  "published": "2026-09-11",
  "keywords": ["bold text for linkedin", "instagram bold text", "how to bold text on linkedin", "bold text generator", "bold unicode", "bold font for social media"],
  "related_tools": [("bold-text-generator", "Bold Text Generator"), ("fancy-text-generator", "Fancy Text Generator"), ("strikethrough-text-generator", "Strikethrough Text Generator"), ("small-text-generator", "Small Text Generator")],
  "body": [
   ("p", "Open a LinkedIn post box or an Instagram bio and look for the bold button. There is not one. Yet you have seen bold headlines in both, so how do people do it? The answer is that the bold text is not formatting at all, it is a set of different characters that happen to look bold. This guide explains how that works, where it pastes reliably, and when you should avoid it. You can make bold text instantly with the free <a href=\"../tools/bold-text-generator.html\">Bold Text Generator</a>."),
   ("h2", "Why there is no bold button"),
   ("p", "In a word processor, bold is an instruction attached to your text: the letters stay the same, and a hidden flag says draw these ones heavier. That flag has to be stored somewhere alongside the text. Social boxes like LinkedIn, Instagram and most chat apps deliberately accept only plain text, with nowhere to keep that flag, so if you paste bold text copied from a document, the box keeps the letters and discards the bold. That is why there is no bold button: the field has no way to store what it would do."),
   ("p", "Bold text generators get around this by never using formatting in the first place. Instead of taking the letter B and flagging it as bold, they swap it for a completely different character that was designed to look like a bold B and already exists in Unicode."),
   ("h2", "Where the bold characters come from"),
   ("p", "Unicode, the universal catalogue of characters, includes a block called Mathematical Alphanumeric Symbols. It was created so mathematicians could write a bold vector or a bold matrix and have it mean something precise, and it contains complete bold alphabets as real, separate characters: a bold serif set, a bold sans-serif set, bold italic, bold script and bold fraktur. A bold text tool simply maps each letter you type to its counterpart in one of these sets."),
   ("p", "So when you paste a bold headline into LinkedIn, you are not sending a bold command, you are sending genuine bold characters. The box has nothing to strip, because the boldness is baked into the characters themselves. That is the whole reason it survives where copied-from-Word bold does not."),
   ("table", ["Style", "Best for", "Note"], [["Bold serif", "Headlines, most complete", "Includes digits"], ["Bold sans", "Clean modern look", "Includes digits"], ["Bold italic", "Emphasis with slant", "Letters only"], ["Bold script", "Decorative flourishes", "Letters only"]]),
   ("tool", "bold-text-generator", "Bold Text Generator", "Type once and copy bold serif, bold sans, bold italic, bold script or bold fraktur. Pastes into LinkedIn, Instagram and other boxes with no bold button."),
   ("h2", "Where it works and where it breaks"),
   ("p", "Because these are standard Unicode characters, they paste into most places that accept plain text: LinkedIn posts and headlines, Instagram bios and captions, Facebook, X, WhatsApp, Discord and many more. Occasionally a platform filters certain ranges, or a device lacks the glyph and shows an empty box, in which case a different bold style, usually bold serif or bold sans, renders where a fancier one does not."),
   ("p", "One thing worth checking is that the destination actually allows the characters at all. A handful of forms sanitise input down to basic Latin letters and will drop them; if your bold text vanishes on posting, that field is one of the strict ones and there is no workaround short of plain text."),
   ("h2", "Use it sparingly, and here is why"),
   ("callout", "The accessibility and search cost", "Screen readers announce these as mathematical characters, so a bold word can be read aloud as a string of symbol names. Search engines also treat them as different characters, so bold Unicode is effectively invisible to search and to LinkedIn's own search. Keep it to a headline or a single standout word, never a whole post."),
   ("p", "The practical rule is emphasis, not body text. A bold first line on a LinkedIn post catches the eye in the feed; a bold key phrase in a bio stands out. But a whole paragraph in bold Unicode is genuinely harder to read, unfriendly to anyone using a screen reader, and unsearchable. Used as a highlight it is effective, used everywhere it works against you."),
   ("h2", "Which platforms keep bold and which strip it"),
   ("p", "In practice, LinkedIn, Instagram, Facebook, X, WhatsApp, Telegram, Discord and most forums keep bold Unicode, because they store and show whatever characters you paste. The places that strip it are the ones that sanitise input down to plain Latin letters: some sign-up forms, certain content-management fields, and search boxes that normalise your query. A quick test tells you which kind you are dealing with. Paste a bold word, post or save, then reload. If it survives the reload it is stored correctly; if it reverts to plain, that field is sanitising and no bold style will stick. It is worth doing this once on a new platform before you rely on bold in something that matters, like a headline."),
   ("h2", "Common questions"),
   ("p", "<strong>Is the bold text generator free?</strong> Yes, with no account or sign-up. <strong>Will it work on LinkedIn and Instagram?</strong> Yes for the most part, because these are real characters rather than formatting; if one style does not show, try bold serif or bold sans. <strong>Why do numbers or some letters stay normal?</strong> Some bold ranges omit digits or a few letters, so anything without a bold version falls back to plain. <strong>Is my text uploaded?</strong> No, everything runs in your browser."),
   ("p", "Bold text on social media is a small trick with a clear mechanism: not a button you are missing, but real bold characters you can paste. Make them with the <a href=\"../tools/bold-text-generator.html\">Bold Text Generator</a>, and if you want the full range of decorative styles beyond bold, the <a href=\"../tools/fancy-text-generator.html\">Fancy Text Generator</a> covers those too."),
  ],
 },
 {
  "slug": "how-strikethrough-text-works",
  "icon": "🚫",
  "nav_title": "How strikethrough works",
  "headline": "How Strikethrough Text Works (and Why It Pastes Anywhere)",
  "title": "How Strikethrough Text Works and Pastes Anywhere | 123MiniApps",
  "standfirst": "Crossed-out text with no formatting button is not magic. It relies on combining characters, an invisible mark that rides along with each letter.",
  "description": "How strikethrough text works: the combining characters that draw a line through letters, the different stroke styles, where it pastes, and its limits, with a free tool.",
  "published": "2026-09-11",
  "keywords": ["strikethrough text", "how strikethrough works", "cross out text", "strikethrough generator", "combining characters", "crossed out text"],
  "related_tools": [("strikethrough-text-generator", "Strikethrough Text Generator"), ("bold-text-generator", "Bold Text Generator"), ("fancy-text-generator", "Fancy Text Generator"), ("text-formatter", "Text Formatter")],
  "body": [
   ("p", "Crossing out text usually needs a formatting toolbar, and most chat boxes, comment fields and bios do not have one. Yet you can paste crossed-out text into them and it stays crossed out. The mechanism is a neat corner of Unicode called combining characters, and once you understand it the whole effect makes sense. You can produce strikethrough instantly with the free <a href=\"../tools/strikethrough-text-generator.html\">Strikethrough Text Generator</a>."),
   ("h2", "Combining characters, explained"),
   ("p", "Most characters occupy their own space: type an A and it sits in its own slot. A combining character is different. It has no width of its own and instead attaches to the character immediately before it, modifying how that character is drawn. Accents work this way in many languages, an e followed by a combining acute accent renders as an accented e, and strikethrough uses the same idea with a mark that draws a line across the preceding character."),
   ("p", "So to strike through a word, a tool inserts a combining stroke after every visible letter. Each letter now carries its own little line, and because those lines are real characters attached to real letters, the effect travels with the text when you copy and paste it, even into a box that would throw away ordinary formatting."),
   ("h2", "The different stroke styles"),
   ("p", "There is more than one combining mark that can cross out text, and they look subtly different. A long stroke overlay draws a continuous horizontal line that reads as one bar through the whole word. A short stroke strikes each letter individually. A solidus overlay puts a diagonal slash through each character rather than a horizontal line. None is more correct than the others; they are simply different marks you can choose between for the look you want."),
   ("table", ["Style", "Looks like", "Good for"], [["Long stroke", "One line through the word", "Prices, edits"], ["Short stroke", "A line on each letter", "A denser look"], ["Slash through", "Diagonal slash", "Cancelled or void"]]),
   ("tool", "strikethrough-text-generator", "Strikethrough Text Generator", "Type once and copy long-stroke, short-stroke or slash-through text. Real combining characters that paste into chat, bios and posts."),
   ("h2", "Where you would actually use it"),
   ("p", "Strikethrough carries a specific meaning that plain text cannot: this was true, and now it is not. That makes it useful for showing an old price beside a new one, marking a to-do item as done without deleting it, indicating an edit or correction in a message, or a bit of dry humour where you cross out one word and follow it with another. In all of these, the crossed-out text stays visible, which is the point, you are showing the change, not hiding it."),
   ("p", "Because it works through combining characters rather than a formatting button, you can do this in places that have no formatting at all: a comment, a chat message, a profile bio, a spreadsheet cell. That reach is exactly why the technique is popular."),
   ("h2", "The limits worth knowing"),
   ("callout", "It is decorative, not semantic", "Screen readers do not announce the strike, so to someone listening, crossed-out text reads exactly like normal text. Never rely on strikethrough alone to convey that something is cancelled or wrong if the meaning matters; say it in words too."),
   ("p", "A few older apps or unusual fonts render combining strokes imperfectly, so the line may sit slightly high or low, and pasting into a system that normalises text can occasionally drop the marks. For everyday use in modern apps it is reliable, but treat it as a visual effect rather than a guaranteed, meaningful signal, and keep anything important stated in plain words as well."),
   ("h2", "Unicode strikethrough versus the double-tilde style"),
   ("p", "Some apps have their own strikethrough that is not Unicode at all. In Slack, Discord and WhatsApp you can wrap text in tildes and the app renders it struck through using real formatting, which is cleaner and more reliable inside that app. The catch is that the tilde syntax only works in the app that understands it: copy that struck-through text elsewhere and it either loses the effect or shows the raw tildes. Unicode strikethrough is the opposite trade: slightly less crisp, but it travels anywhere because the strike lives in the characters themselves. Use an app's native tilde syntax while you stay inside that app, and Unicode strikethrough when the result has to survive being pasted somewhere else."),
   ("h2", "Common questions"),
   ("p", "<strong>Is the strikethrough generator free?</strong> Yes, with no account or sign-up. <strong>Will it work in chat and social apps?</strong> Yes in most, because it uses real combining characters rather than formatting; if one mark looks off, try another style. <strong>Why does the line sometimes look slightly misaligned?</strong> A few fonts position the combining stroke imperfectly; switching style or app usually fixes it. <strong>Is my text uploaded?</strong> No, the conversion runs entirely in your browser."),
   ("p", "Strikethrough is a small effect with a tidy explanation: a combining line attached to each letter, which is why it survives a plain text box. Create it with the <a href=\"../tools/strikethrough-text-generator.html\">Strikethrough Text Generator</a>, and for bold, italic and other pasteable styles, see the <a href=\"../tools/bold-text-generator.html\">Bold Text Generator</a>."),
  ],
 },
 {
  "slug": "small-text-superscript-subscript-explained",
  "icon": "🔡",
  "nav_title": "Small text explained",
  "headline": "Small Text Explained: Superscript, Subscript and Small Caps",
  "title": "Small Text Explained: Superscript & Subscript | 123MiniApps",
  "standfirst": "Tiny text is not a smaller font size. It is three separate sets of Unicode characters, each borrowed from a different purpose, and each incomplete.",
  "description": "How small text works: the superscript, subscript and small-caps Unicode characters behind tiny text, why some letters do not shrink, and where to use it, with a free tool.",
  "published": "2026-09-11",
  "keywords": ["small text generator", "tiny text", "superscript text", "subscript text", "small caps", "how small text works"],
  "related_tools": [("small-text-generator", "Small Text Generator"), ("fancy-text-generator", "Fancy Text Generator"), ("bold-text-generator", "Bold Text Generator"), ("text-to-ascii", "Text to ASCII")],
  "body": [
   ("p", "The tiny text people put in bios and usernames looks like a shrunk font, but a plain text box cannot store a font size, so that is not what is happening. Small text is actually three separate sets of Unicode characters that happen to be drawn small. Knowing which is which explains why some letters shrink and others stubbornly do not. You can make all three with the free <a href=\"../tools/small-text-generator.html\">Small Text Generator</a>."),
   ("h2", "Three different small alphabets"),
   ("p", "There is no single small alphabet in Unicode. Instead there are three ranges, each created for a different reason, that a small-text tool borrows from. Superscript characters are the raised ones used for footnotes and exponents. Subscript characters are the lowered ones used in chemistry, like the numbers in a chemical formula. Small capitals are miniature uppercase letters used in phonetics and typography. Each looks small, but they sit at different heights and come from different places."),
   ("table", ["Style", "Originally for", "Coverage"], [["Superscript", "Footnotes, exponents", "Most letters and all digits"], ["Small caps", "Phonetics, typography", "Full alphabet"], ["Subscript", "Chemistry, maths", "A few letters and all digits"]]),
   ("h2", "Why some letters refuse to shrink"),
   ("p", "This is the part that surprises people. Because these ranges were built for narrow purposes and not as a general alphabet, they are incomplete. Superscript is fairly full for lowercase letters and complete for digits. Small caps covers the whole alphabet well. But subscript is the sparsest by far: only a handful of letters ever got a subscript form, because chemistry and maths simply never needed the rest. So when you convert a word to subscript, any letter without a small version falls back to normal, and the result comes out half shrunk."),
   ("p", "That is not a bug in the tool, it is a gap in Unicode itself. The tool leaves the original letter in place rather than inventing a character that does not exist, which is why superscript and small caps give the cleanest results and subscript is best reserved for short strings or numbers."),
   ("tool", "small-text-generator", "Small Text Generator", "Type once and copy superscript, small caps or subscript. Real Unicode tiny letters that paste into bios, usernames and posts."),
   ("h2", "Where small text fits"),
   ("p", "Tiny text is a subtle aesthetic touch. A superscript tagline under a username, a small-caps label in a bio, a delicate line that reads as understated rather than shouty. It works in most places that accept plain text, because these are real characters and not a font setting, so a bio field or a caption keeps them where it would discard an actual font change."),
   ("callout", "Keep it short", "Small text is genuinely hard to read at length and is announced awkwardly, letter by letter or not at all, by screen readers. It is charming for a username or a one-line label and painful for a paragraph. Use it as a flourish, not for anything a reader actually needs to take in."),
   ("h2", "A note on the difference from a smaller font"),
   ("p", "It is worth being clear that small text and a smaller font size are not the same thing, and the difference matters. A smaller font size is a formatting instruction that a rich editor can apply to ordinary letters, and it is fully readable and searchable. Small Unicode text is a swap to different characters, which is what lets it survive a plain box but also what makes it less readable and invisible to search. If you are writing somewhere that has a font size control, use that; the Unicode trick is for the many places that do not."),
   ("h2", "When small text is the wrong choice"),
   ("p", "Small text is a decorative flourish, and there are places it quietly backfires. Do not use it for anything a search box needs to match, because a superscript or small-caps word will not be found by a normal search. Avoid it in a display name people need to read aloud or type, and keep it out of anything that must be accessible, since screen readers handle these characters poorly. It is also a poor fit for numbers people must read precisely, like a phone number or a price, where the shrunk digits are easy to misread. Reserve it for the aesthetic touches it is good at, a subtitle in a bio or a subtle label, and use ordinary text everywhere the content actually matters."),
   ("h2", "Common questions"),
   ("p", "<strong>Is the small text generator free?</strong> Yes, with no account or sign-up. <strong>Will it work in my bio?</strong> Usually yes, because the styles are real Unicode characters; prefer superscript or small caps for the most complete coverage. <strong>Why is my subscript half normal?</strong> The subscript range only covers a few letters, so the rest fall back to plain. <strong>Is my text uploaded?</strong> No, everything runs in your browser."),
   ("p", "Small text makes sense once you see it as three borrowed alphabets rather than a shrink ray: superscript, small caps and subscript, each useful and each with gaps. Make them with the <a href=\"../tools/small-text-generator.html\">Small Text Generator</a>, and for the wider family of pasteable styles, try the <a href=\"../tools/fancy-text-generator.html\">Fancy Text Generator</a>."),
  ],
 },
 {
  "slug": "does-bionic-reading-work",
  "icon": "⚡",
  "nav_title": "Does bionic reading work",
  "headline": "Does Bionic Reading Actually Work? What the Evidence Says",
  "title": "Does Bionic Reading Actually Work? The Evidence | 123MiniApps",
  "standfirst": "Bolding the first part of each word feels like it should speed you up. The honest answer is that it helps some people, and the studies are not convinced.",
  "description": "Does bionic reading work? How bolding the start of each word is meant to help, what controlled studies actually found, and who benefits, with a free converter to try it.",
  "published": "2026-09-11",
  "keywords": ["does bionic reading work", "bionic reading", "bionic reading evidence", "speed reading", "read faster", "bionic reading converter"],
  "related_tools": [("bionic-reading-converter", "Bionic Reading Converter"), ("readability-checker", "Readability Checker"), ("word-counter", "Word Counter"), ("text-formatter", "Text Formatter")],
  "body": [
   ("p", "Bionic reading is the idea that bolding the first few letters of every word helps you read faster. It spread quickly because it feels plausible and looks striking. But does it actually work? The honest answer is that it helps some people subjectively and the controlled evidence has not backed up the speed claims. This guide explains the mechanism and what the research found, so you can judge it for yourself with the free <a href=\"../tools/bionic-reading-converter.html\">Bionic Reading Converter</a>."),
   ("h2", "What bionic reading actually does"),
   ("p", "The technique bolds the opening portion of each word, usually the first one to several letters depending on word length, and leaves the rest in normal weight. The stated theory is that these bold openings act as fixation points, the spots your eyes naturally land on, and that your brain can recognise a familiar word from its first letters and shape without reading every character. In that account, the bold prefixes let your eyes hop from word to word more efficiently."),
   ("p", "It is a reasonable-sounding story built on a real fact: skilled readers do not read letter by letter, they recognise whole words and even predict them from context and shape. The open question is whether artificially bolding word openings actually improves on the reading your brain already does so well."),
   ("h2", "What the studies found"),
   ("p", "This is where the popular claim and the evidence part ways. Independent studies that measured reading speed and comprehension with and without bionic-style bolding have generally found no reliable improvement, and some found a small slowdown. Results also vary a great deal between individuals, which is exactly the pattern you see when an effect is weak or driven by preference rather than a genuine mechanism."),
   ("callout", "The honest summary", "As of now, controlled research does not support the claim that bionic reading makes people read faster or understand more on average. That does not mean it is useless to you personally, only that it is not the proven speed boost it is often sold as."),
   ("p", "There is an important gap between feeling faster and being faster. Bolded openings can make a page feel more navigable and less daunting, which is a real and valuable experience, but feeling more engaged is not the same as measurably higher words per minute, and studies that separate the two tend to find the feeling without the speed."),
   ("tool", "bionic-reading-converter", "Bionic Reading Converter", "Paste any text and bold the opening of each word, with an adjustable fixation. Copies real bold Unicode so you can read it here or paste it elsewhere."),
   ("h2", "Who might genuinely benefit"),
   ("p", "Averages hide individuals, and some readers report that bolded word openings help them stay on the line and resist skipping, particularly with long or dense material or when concentration is hard to hold. People with attention difficulties sometimes find it useful as a focus aid rather than a speed tool. None of this is settled science, but a reading aid that some people find genuinely comfortable is worth having, as long as nobody is promised a speed increase that the evidence does not support."),
   ("p", "The sensible way to decide is to try it on your own material and notice honestly whether it helps, rather than assuming it must because it is popular. Adjust how much of each word is bolded: a light setting gives a gentle cue, a heavy one is more forceful but can start to feel cluttered."),
   ("h2", "How to try it fairly"),
   ("p", "Convert a piece of text you would normally read, set the fixation somewhere in the middle, and read a few paragraphs. Then read a similar piece as plain text. Pay attention to whether you actually finished sooner and understood as much, not just to whether the bold version looked more inviting. If it helps you, use it; if it does not, you have lost nothing, and you have avoided paying for a browser extension that promises more than the research delivers."),
   ("h2", "Setting the fixation, and a note on dyslexia"),
   ("p", "If you do try it, the fixation setting matters more than people expect. A light fixation bolds only the first letter or two and reads almost like normal text with a gentle nudge; a heavy fixation bolds most of each word and can start to feel busy, with so much bold that the cue loses its meaning. Somewhere in the middle usually feels most natural, so adjust it to your own eye rather than leaving it at a default. As for dyslexia, which comes up often in these discussions, the picture is the same as elsewhere: some people with dyslexia report that it helps them hold the line, but there is no strong evidence that bionic-style bolding is a reliable dyslexia aid, and established approaches such as wider spacing and specific fonts have better support. Treat it as one option to try, not a treatment."),
   ("h2", "Common questions"),
   ("p", "<strong>Is the bionic reading converter free?</strong> Yes, with no account or sign-up. <strong>Does it really make you read faster?</strong> Controlled studies have not found a consistent speed or comprehension gain, though some people find it more comfortable, so try it and judge for yourself. <strong>Can I paste the result elsewhere?</strong> Yes, it uses real bold Unicode characters. <strong>Is my text uploaded?</strong> No, the conversion runs entirely in your browser."),
   ("p", "Bionic reading is a genuinely interesting idea that the evidence has not yet vindicated as a speed tool, but that some readers still like. Try it honestly with the <a href=\"../tools/bionic-reading-converter.html\">Bionic Reading Converter</a>, and if your real goal is clearer writing rather than faster reading, the <a href=\"../tools/readability-checker.html\">Readability Checker</a> is the better place to start."),
  ],
 },
 {
  "slug": "what-to-use-a-word-repeater-for",
  "icon": "🔁",
  "nav_title": "Uses for a word repeater",
  "headline": "What to Use a Word Repeater For (and How Separators Help)",
  "title": "What to Use a Word Repeater For | 123MiniApps",
  "standfirst": "Repeating text by hand is slow and error prone past a few copies. The real skill is choosing the right separator for what you are building.",
  "description": "Practical uses for a word repeater: test data, numbered lists, placeholders and templates, plus how separators turn repeated text into something you can paste anywhere.",
  "published": "2026-09-11",
  "keywords": ["word repeater", "repeat text", "repeat word", "text repeater", "duplicate text", "repeat text online"],
  "related_tools": [("word-repeater", "Word Repeater"), ("remove-duplicate-lines", "Remove Duplicate Lines"), ("find-and-replace", "Find and Replace"), ("word-counter", "Word Counter")],
  "body": [
   ("p", "Repeating a word or phrase a set number of times sounds trivial until you have to do it fifty times by hand and keep the separators consistent. A word repeater does the counting and spacing for you, and the part that actually makes it useful is choosing the right separator for the job. This guide covers what people genuinely use repetition for and how the separator changes everything, with the free <a href=\"../tools/word-repeater.html\">Word Repeater</a> to try it."),
   ("h2", "The real uses for repeated text"),
   ("p", "Repetition turns up more often in practical work than you might expect. Filling a spreadsheet column with the same test value, generating a block of placeholder lines to check how a layout wraps, padding a document to a target length while drafting, building a quick numbered list to fill in later, or producing a repeated phrase for a template or a mail merge. In each case the point is not the words themselves but having exactly the right number of them, spaced exactly right, without hand-counting."),
   ("p", "Doing this by hand is where mistakes creep in: an extra space here, a missing line break there, a miscount that leaves you with forty-nine copies instead of fifty. A repeater removes all of that, which matters most precisely when the output is going somewhere strict, like a spreadsheet or a config file that expects a specific structure."),
   ("h2", "The separator is the whole trick"),
   ("p", "The separator is the character or characters placed between each copy, and it is what turns a pile of repeated words into something usable. The same word repeated thirty times is a different thing depending on what sits between the copies."),
   ("table", ["Separator", "Result", "Paste it into"], [["New line", "One copy per line", "Lists, text files"], ["Comma", "A, A, A", "Simple lists, CSV cells"], ["Space", "A A A on one line", "Filler, spacing tests"], ["Custom", "A | A | A and the like", "Delimited formats"]]),
   ("p", "Choosing the separator to match the destination is what saves the real time. A new line gives you a ready-made column to paste into a spreadsheet. A comma builds a quick inline list. A custom separator like a pipe or a bracketed pattern produces delimited output you can drop straight into a format that expects it."),
   ("tool", "word-repeater", "Word Repeater", "Repeat a word or phrase any number of times with a space, new line, comma or custom separator, optionally numbered, then copy the result."),
   ("h2", "Numbering turns it into a list builder"),
   ("p", "Adding a number to each copy changes the tool from a repeater into a fast scaffold for ordered lists. Ten numbered blank prompts to fill in, a set of labelled placeholder rows, a sequence of identical steps you will edit afterwards. It is a small option that quietly covers a common need: you rarely want a bare repeated word, but you often want a numbered frame to work into."),
   ("h2", "A word on not being spammy"),
   ("callout", "Repetition has a bad reputation for a reason", "Mass-repeated text is the raw material of spam and of keyword stuffing, both of which are counterproductive: platforms filter obvious repetition, and search engines penalise pages that pad themselves with repeated words. Use a repeater for structure and testing, not to inflate a post or a page."),
   ("p", "The legitimate uses above are about structure and speed, not about drowning something in filler. If you find yourself repeating a keyword to look more relevant to search engines, that is the one case where the tool will actively hurt you, because modern ranking systems treat repetition as a negative signal rather than a positive one. Keep repetition to scaffolding and data, and keep real writing varied."),
   ("h2", "Repeat and combine are two sides of one job"),
   ("p", "It helps to see repeating and its opposite as a pair. Repeating takes one item and multiplies it with a chosen separator; combining takes many items and joins them with a chosen separator. They share the same core idea, that the separator is what makes the output usable, and you often need both in sequence. A common workflow is to repeat a template line to the count you need, paste it into an editor, fill in the specifics, then deduplicate or join the results into the final format. Knowing that the separator is the important choice in both directions is what lets you move text between a list, a delimited string and a spreadsheet column without retyping anything."),
   ("h2", "Common questions"),
   ("p", "<strong>Is the word repeater free?</strong> Yes, with no account or sign-up. <strong>How many copies can I make?</strong> Up to ten thousand at once, and it still runs instantly because everything happens in your browser. <strong>Can I put each copy on its own line?</strong> Yes, choose the new line separator, or a comma, space, nothing or a custom separator. <strong>Is my text uploaded?</strong> No, the tool runs entirely in your browser."),
   ("p", "A word repeater is a small utility that earns its place by getting the count and the separators right so you do not have to. Use it with the <a href=\"../tools/word-repeater.html\">Word Repeater</a>, and when you need to go the other way and strip duplicates out of a list, the <a href=\"../tools/remove-duplicate-lines.html\">Remove Duplicate Lines</a> tool is its natural counterpart."),
  ],
 },
]
