#!/usr/bin/env python3
# ============================================
# 123MiniApps.online v2.0
# File: build-css.py
# Purpose: Flatten the @import chain into one file.
#
# WHY THIS EXISTS
# ---------------
# main.css uses @import, which is convenient in
# development (each layer is a separate, debuggable
# file) but costly in production.
#
# @import is discovered by the CSS parser, not the
# HTML parser. So the browser must:
#
# 1. Download main.css (1 round trip)
# 2. Parse it, find 9 @imports
# 3. Download those 9 files (another round trip)
# 4. Only now can it build the CSSOM and paint
#
# CSS is render-blocking, so the page shows nothing
# until all of that finishes. The preload scanner
# cannot help, because it only reads HTML, it never
# sees URLs hidden inside a stylesheet.
#
# Concatenating removes an entire round trip from the
# critical path. On a 4G connection with ~150ms RTT
# that is roughly 150-300ms off first paint, for zero
# behavioural change.
#
# Usage: python3 build-css.py
# Output: assets/css/main.min.css
# ============================================

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CSS_DIR = os.path.join(HERE, "assets", "css")
OUTPUT = os.path.join(CSS_DIR, "main.min.css")

# Cascade order matters, later rules win, so this sequence
# must match the @import order in main.css exactly.
ORDER = [
    "reset.css",
    "design-tokens.css",
    "typography.css",
    "spacing.css",
    "shadows.css",
    "animations.css",
    "layout.css",
    "components.css",
    "themes.css",
]


def minify(css):
    """
    Conservative minification. Deliberately does NOT touch
    anything inside strings or url(), and does not attempt
    to shorten values, the goal is safe byte reduction,
    not maximum compression.
    """
    # Protect strings and url() contents from every later step
    stash = []

    def protect(match):
        stash.append(match.group(0))
        return f"\x01{len(stash) - 1}\x01"

    css = re.sub(r'url\([^)]*\)|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', protect, css)

    # Strip comments, but keep /*! ... */ licence banners
    css = re.sub(r"/\*(?!!)[\s\S]*?\*/", "", css)

    # Collapse whitespace
    css = re.sub(r"\s+", " ", css)
    # Collapse space around structural chars and the >/~ combinators.
    # NOTE: '+' is deliberately NOT in this class. Inside calc()/min()/max()/
    # clamp() the '+' operator REQUIRES whitespace on both sides, e.g.
    # calc(var(--space-8) + 68px). Stripping it produces calc(2rem+68px),
    # which browsers reject and resolve to a garbage value. The few extra
    # bytes from keeping "a + b" spacing in selectors are worth it.
    css = re.sub(r"\s*([{}:;>~])\s*", r"\1", css)

    # Drop the final semicolon in each block
    css = css.replace(";}", "}")

    # Restore protected regions
    css = re.sub(r"\x01(\d+)\x01", lambda m: stash[int(m.group(1))], css)

    return css.strip()


def build():
    parts = [
        "/*! 123MiniApps.online v2.0, main.min.css\n"
        " * Generated by build-css.py. Do not edit directly.\n"
        " * Edit the source files in assets/css/ and re-run the script.\n"
        " */"
    ]

    total_raw = 0

    for name in ORDER:
        path = os.path.join(CSS_DIR, name)
        with open(path, encoding="utf-8") as fh:
            source = fh.read()

        total_raw += len(source.encode("utf-8"))
        parts.append(f"/* ---- {name} ---- */")
        parts.append(minify(source))

    output = "\n".join(parts) + "\n"

    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(output)

    final = len(output.encode("utf-8"))
    saved = total_raw - final

    print(f"  concatenated {len(ORDER)} files")
    print(f"  raw       : {total_raw:,} bytes")
    print(f"  minified  : {final:,} bytes")
    print(f"  saved     : {saved:,} bytes ({saved / total_raw * 100:.1f}%)")
    print(f"  round trips: 2 -> 1")
    print(f"\n  wrote {os.path.relpath(OUTPUT, HERE)}")


if __name__ == "__main__":
    build()
